<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap / CSS -->
    <link rel="stylesheet" href="/styles/custom-perfil.css">

    <title>Perfil Candidato</title>

    <script type="text/javascript">
        let experiencias = <?php echo json_encode($this->view->perfilExperiencia) ?>;
        let competencias =  <?php echo json_encode($this->view->perfilCompetencia) ?>;
        let formacoes =  <?php echo json_encode($this->view->perfilFormacao) ?>;
    </script>
                
</head>

<body>
    <!--Header-->
    <nav class="navbar navbar-expand-lg navbar-dark" id="header">
        <div class="container-fluid background-navbar">
            <a class="navbar-brand" href="#"><img src="/images/global/logo.svg" alt=""></a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">
                <img src="/images/global/navbar-button.svg" class="navbar-button">
            </button>

            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" aria-current="page" href="/">Home</a>
                    <a class="nav-link active" href="/perfil_ver">Perfil</a>
                    <a class="nav-link" href="/#sobre_nos">Sobre</a>
                    <a class="nav-link" href="/#quem_somos">Quem Somos</a>
                    <a class="nav-link" href="/#nossa_equipe">Nossos Líderes</a>
                    <a class="nav-link" href="/#vagas_abertas">Trabalhe Conosco</a>
                    <a class="nav-link" href="/#contate_nos">Contato</a>
                    <a class="nav-link" href="/usuario_sair">Sair</a>
                </div>
            </div>
        </div>
    </nav>

    <!--body-->
    <form action="requisitante.php" method="post" id="formulario">
        <div class="container">

            <!--parte de cima do perfil-->
            <div class="row d-flex justify-content-center perfil-box">

                <div class="row row-img-names">
                    <div class="img-perfil"></div>

                    <div class="names">
                        <h1 class="nome-perfil"><?=$_SESSION['nome']?></h1>
                        <h2 class="nome-usuario"><?=$_SESSION['login_user']?></h2>
                    </div>
                </div>

                <p class="mb-3 descricao-perfil">
                    <?= isset($this->view->detalhesPerfilCandidato->sobre) ? $this->view->detalhesPerfilCandidato->sobre : ''; ?>
                </p>

                <div class="buttons">
                    <a href="/editar_perfil">
                        <button type="button" class="btn btn-outline-primary mb-2">Editar Perfil</button>
                    </a>
                    <a href="/vaga_candidatada_ver">
                        <button type="button" class="btn btn-outline-primary mb-2">Vagas Candidatadas</button>
                    </a>
                </div>
            </div>

            <hr class="mb-4">

            <!--parte de baixo do perfil-->

            <!--dados pessoais-->
            <div class="title">
                <h2 class="title-2">Dados Pessoais</h2>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="colsm-2 form-label">Data de Nascimento</label>
                <div class="col-sm-10">
                    <input type="date" class="form-control" id="colFormLabel" placeholder="" name="data-de-nascimento"
                        readonly value="<?= isset($this->view->detalhesPerfilCandidato->data_nasc) ? $this->view->detalhesPerfilCandidato->data_nasc : ''; ?>">
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="colsm-2 form-label">Sexo</label>
                <div class="col-sm-10">
                    <?php
                        $sexo = isset($this->view->detalhesPerfilCandidato->sexo) ? $this->view->detalhesPerfilCandidato->sexo : '';
                        if($sexo== 1) {
                            $sexo = 'Masculino';
                        } else if($sexo == 2) {
                            $sexo = 'Feminino';
                        } 
                    ?>
                    <input type="text" class="form-control" id="colFormLabel" placeholder="" name="sexo" 
                    readonly value="<?=$sexo?>">
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">CPF</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="colFormLabel" placeholder="" name="cpf" 
                    readonly value="<?= isset($this->view->detalhesPerfilCandidato->cpf) ? $this->view->detalhesPerfilCandidato->cpf : ''; ?>">
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">CNPJ</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="colFormLabel" placeholder="" name="cnpj" readonly
                    value="<?= isset($this->view->detalhesPerfilCandidato->cnpf) ? $this->view->detalhesPerfilCandidato->cnpf : ''; ?>">
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Disponibilidade</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="colFormLabel" placeholder="" name="disponibilidade"
                        readonly value="<?= isset($this->view->detalhesPerfilCandidato->disponibilidade) ? $this->view->detalhesPerfilCandidato->disponibilidade : ''; ?>">
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Status</label>
                <div class="col-sm-10">
                    <?php
                        $status = isset($this->view->detalhesPerfilCandidato->c_status) ? $this->view->detalhesPerfilCandidato->c_status : '';
                        if($status== 1) {
                            $status = 'Desempregado';
                        } else if($status == 2) {
                            $status = 'Trabalhando';
                        }
                    ?>
                    <input type="text" class="form-control" id="colFormLabel" placeholder="" name="status" readonly
                        value="<?=$status?>">
                </div>
            </div>

            <!--contato-->

            <div class="title">
                <h2 class="title-2">Contato</h2>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="colsm-2 form-label">Telefone</label>
                <div class="col-sm-10">
                    <input type="tel" class="form-control" id="colFormLabel" placeholder="" name="telefone" readonly
                        value="<?= isset($this->view->detalhesPerfilCandidato->telefone) ? $this->view->detalhesPerfilCandidato->telefone : '';?>">
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="colsm-2 form-label">Celular</label>
                <div class="col-sm-10">
                    <input type="tel" class="form-control" id="colFormLabel" placeholder="" name="celular" readonly
                        value="<?= isset($this->view->detalhesPerfilCandidato->celular) ? $this->view->detalhesPerfilCandidato->celular : ''; ?>">
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">E-mail</label>
                <div class="col-sm-10">
                    <input type="email" class="form-control" id="colFormLabel" placeholder="" name="email" readonly
                        value="<?= isset($this->view->detalhesPerfilCandidato->email) ? $this->view->detalhesPerfilCandidato->email : ''; ?>">
                </div>
            </div>

            <!--residencia-->

            <div class="title">
                <h2 class="title-2">Residência</h2>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="colsm-2 form-label">CEP</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="colFormLabel" placeholder="" name="cep" readonly
                        value="<?= isset($this->view->detalhesPerfilCandidato->cep) ? $this->view->detalhesPerfilCandidato->cep : ''; ?>">
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="colsm-2 form-label">Estado</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="colFormLabel" placeholder="" name="estado" readonly
                        value="<?= isset($this->view->detalhesPerfilCandidato->estado) ? $this->view->detalhesPerfilCandidato->estado : ''; ?>">
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Cidade</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="colFormLabel" placeholder="" name="cidade" readonly
                        value="<?= isset($this->view->detalhesPerfilCandidato->cidade) ? $this->view->detalhesPerfilCandidato->cidade : ''; ?>">
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Bairro</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="colFormLabel" placeholder="" name="bairro" readonly
                        value="<?= isset($this->view->detalhesPerfilCandidato->bairro) ? $this->view->detalhesPerfilCandidato->bairro : ''; ?>">
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Rua</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="colFormLabel" placeholder="" name="rua" readonly
                        value="<?= isset($this->view->detalhesPerfilCandidato->rua) ? $this->view->detalhesPerfilCandidato->rua : ''; ?>">
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Número</label>
                <div class="col-sm-10 mb-3">
                    <input type="number" class="form-control" id="colFormLabel" placeholder="" name="cidade" readonly
                        value="<?= isset($this->view->detalhesPerfilCandidato->num_casa) ? $this->view->detalhesPerfilCandidato->num_casa : ''; ?>">
                </div>
            </div>

            <!--Experiências-->
            <div class="title">
                <h2 class="title-2">Experiências</h2>
            </div>

            <div id="Exp">
                <div class="subtitle">
                    <h3 class="title-3">Experiência</h3>
                    <h3 class="numExp">1</h3>
                </div>

                <div class="row mb-3">
                    <select class="col form-select cl-exp-formacao form3" aria-label="Experiência"
                        name="exp-fomacao-1" readonly>
                        <option value="0">Experiência</option>
                        <option value="1">Administrativa</option>
                        <option value="2">Elétrica</option>
                        <option value="3">Eletrônica</option>
                        <option value="4">Recursos Humanos</option>
                        <option value="5">Redes</option>
                        <option value="6">Contábil</option>
                        <option value="7">Programação</option>
                        <option value="8">Logística</option>
                    </select>

                    <select class="col form-select cl-exp-status form3" aria-label="Status" name="exp-status-1" readonly>
                        <option value="0">Status</option>
                        <option value="1">Experiência Qualquer</option>
                        <option value="2">Júnior</option>
                        <option value="3">Pleno</option>
                        <option value="4">Sênior</option>
                    </select>
                </div>

                <div class="row">
                    <label for="colFormLabel" class="col-sm-2 form-label exp-label">Anos de Experiência:</label>
                    <div class="col number mb-3">
                        <input type="number" class="form-control cl-exp-anos-experiencia" style="min-width: 50px;" id="colFormLabel"
                            placeholder="" name="exp-anos-experiencia-1" readonly>
                    </div>
                </div>
            </div>

            <!--Competências-->
            <div class="title">
                <h2 class="title-2">Competências</h2>
            </div>

            <div id="Comp">
                <div class="subtitle">
                    <h3 class="title-3">Competência</h3>
                    <h3 class="numComp">1</h3>
                </div>

                <div class="row mb-3">
                    <select class="col form-select cl-comp-nome form3" aria-label="Nome" name="comp-nome-1" readonly>
                        <option value="0">Nome</option>
                        <option value="1">Gestão de Pessoas</option>
                        <option value="2">Análise de Requisitos</option>
                        <option value="3">Java</option>
                        <option value="4">ERP</option>
                        <option value="5">Prestações de Contas</option>
                        <option value="6">Escrituração Fiscal</option>
                        <option value="7">Manutenção de Motores Trifásicos</option>
                        <option value="8">Gestão de Projetos</option>
                        <option value="9">Planejamento de Armazenagem de Mercadorias</option>
                        <option value="10">Inglês</option>
                    </select>

                    <select class="col form-select cl-comp-grau form3" aria-label="Grau" name="comp-grau-1" readonly>
                        <option value="0">Grau</option>
                        <option value="1">Básico</option>
                        <option value="2">Intermediário</option>
                        <option value="3">Avançado</option>
                    </select>
                </div>

                <div class="row">
                    <div class="col mb-3">
                        <select class="col form-select cl-comp-status form3" style="margin-left: 0;" aria-label="Status" name="comp-status-1" readonly>
                            <option value="0">Status</option>
                            <option value="1">Iniciante</option>
                            <option value="2">Em Desenvolvimento</option>
                            <option value="3">Concluído</option>
                        </select>
                    </div>
                </div>
            </div>

            <!--Formações-->
            <div class="title">
                <h2 class="title-2">Formações</h2>
            </div>

            <div id="Form">
                <div class="subtitle">
                    <h3 class="title-3">Formação</h3>
                    <h3 class="numForm">1</h3>
                </div>

                <div class="row mb-3">
                <select class="col form-select cl-form-tipo form3" aria-label="Tipo" name="form-tipo-1" readonly>
                        <option value="0">Tipo</option>
                        <option value="1">Fundamental</option>
                        <option value="2">Ensino médio</option>
                        <option value="3">Técnico</option>
                        <option value="4">Superior</option>
                    </select>

                    <select class="col form-select cl-form-status form3" aria-label="Status" name="form-status-1" readonly>
                        <option value="0">Status</option>
                        <option value="1">Completo</option>
                        <option value="2">Em Andamento</option>
                        <option value="3">Incompleto</option>
                    </select>
                </div>

                <div class="row">
                    <select class="col form-select cl-form-nome form3" aria-label="Nome" name="form-nome-1" readonly>
                        <option value="0">Nome</option>
                        <option value="1">Análise e Desenvolvimento de Sistemas</option>
                        <option value="2">Redes</option>
                        <option value="3">Ciência da Computação</option>
                        <option value="4">Logística</option>
                        <option value="5">Contabilidade</option>
                        <option value="6">Engenharia Elétrica</option>
                        <option value="7">Engenharia Eletrônica</option>
                        <option value="8">Engenharia de Automação</option>
                        <option value="9">Recursos Humanos</option>
                        <option value="10">Administração</option>
                    </select>

                    <select class="col form-select cl-form-grau form3" aria-label="Grau" name="form-grau-1" readonly>
                        <option value="0">Grau</option>
                        <option value="1">Tecnólogo</option>
                        <option value="2">Graduação</option>
                        <option value="3">Pôs-graduação</option>
                        <option value="4">Mestrado</option>
                        <option value="4">Doutorado</option>
                    </select>
                </div>
            </div>

            <!--Currículo-->
            <div class="title">
                <h2 class="title-2">Currículo</h2>
            </div>

            <div class="row">
                <div class="col col-pdf">
                    <img class="pdf" src="/images/custom-perfil/pdf.svg">
                </div>

                <div class="col col-btns">
                    <div class="buttons">
                        <button type="button" class="btn btn-outline-primary mb-2">
                            <img src="/images/custom-perfil/upload.svg">
                            Upload</button>
                    </div>
                    <div class="buttons">
                        <button type="button" class="btn btn-outline-primary mb-2">
                            <img src="/images/custom-perfil/download.svg">
                            Download</button>
                    </div>
                    <div class="buttons">
                        <button type="button" class="btn btn-outline-primary mb-5">
                            <img src="/images/custom-perfil/view.svg">
                            Visualizar</button>
                    </div>
                </div>
            </div>


            <div class="buttons">
                <a href="perfil_ver">
                    <button type="button" class="btn btn-outline-primary mb-5">Voltar</button>
                </a>
            </div>
        </div>
    </form>

    <!--Footer-->
    <footer class="footer">
        <img src="/images/global/linkedin.svg" class="img-footer" onclick="">
        <img src="/images/global/facebook.svg" class="img-footer" onclick="">
        <img src="/images/global/email.svg" class="img-footer" onclick="">
        <label class="label-footer">+55 (15) 5555-5555</label>
    </footer>

    <!--Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ"
        crossorigin="anonymous"></script>

    <script src="/scripts/manager-scripts/gerar-requisicao-de-vaga.js"></script>
    <script>
        insereExperienciaPerfil();
        insereCompetenciaPerfil();
        insereFormacaoPerfil();
    </script>
</body>

</html>