<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Realizar Teste</title>

    <!-- Bootstrap / CSS -->
    <link rel="stylesheet" href="/styles/custom-atribuir-realizar-teste.css">
    <link rel="stylesheet" href="/styles/pop-up.css">

</head>

<body>

    <!--Header-->
    <nav class="navbar navbar-expand-lg navbar-dark" id="header">
        <div class="container-fluid background-navbar">
            <a class="navbar-brand" href="#"><img src="/images/global/logo.svg" alt=""></a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">
                <img src="/images/global/navbar-button.svg" class="navbar-button">
            </button>

            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" aria-current="page" href="#">Home</a>
                    <a class="nav-link active" href="#">Perfil</a>
                    <a class="nav-link" href="#">Sobre</a>
                    <a class="nav-link" href="#">Quem Somos</a>
                    <a class="nav-link" href="#">Nossos Líderes</a>
                    <a class="nav-link" href="#">Trabalhe Conosco</a>
                    <a class="nav-link" href="#">Contato</a>
                    <a class="nav-link" href="/usuario_sair">Sair</a>
                </div>
            </div>
        </div>
    </nav>

    <!--Pop-up area-->
    <div class="popup-container" id="popup-info">
        <!--onclick="Open('popup-info')"-->
        <!--link rel="stylesheet" href="../../../../Public/styles/pop-up.css">-->
        <!--<script src="../../../../Public/scripts/general-scripts/pop-up.js"></script>-->
        <div class="popup-content">
            <div class="popup-close" title="Close" onclick="Close(this)">
                <img src="/images/global/close.svg">
            </div>

            <img src="/images/pop-up/info.svg" class="popup-img">

            <h1 class="popup-title">Realizar Teste</h1>

            <p class="popup-description">O teste possui apenas uma resposta certa para cada pergunta e não possui tempo
                limite para a realização.</p>

            <button type="button" class="popup-btn popup-btn-width" onclick="Close(this)">
                Entendi!
            </button>
        </div>
    </div>

    <div class="popup-container" id="popup-confirm">
        <!--onclick="Open('popup-confirm')"-->
        <!--link rel="stylesheet" href="../../../../Public/styles/pop-up.css">-->
        <!--<script src="../../../../Public/scripts/general-scripts/pop-up.js"></script>-->
        <div class="popup-content">
            <div class="popup-close" title="Close" onclick="Close(this)">
                <img src="/images/global/close.svg">
            </div>

            <img src="/images/pop-up/alert.svg" class="popup-img">

            <h1 class="popup-title">Finalizar Teste</h1>

            <p class="popup-description">Tem certeza que deseja finalizar o teste? Você não poderá mais alterar suas
                respostas.</p>

            <button class="popup-btn popup-btn-width" onclick="Confirm(this)">
                Confirmar
            </button>

            <button type="button" class="popup-btn-link" onclick="Close(this)">
                Voltar
            </button>
        </div>
    </div>

    <div class="popup-container" id="popup-desistir">
        <!--onclick="Open('popup-desistir')"-->
        <!--link rel="stylesheet" href="../../../../Public/styles/pop-up.css">-->
        <!--<script src="../../../../Public/scripts/general-scripts/pop-up.js"></script>-->
        <div class="popup-content">
            <div class="popup-close" title="Close" onclick="Close(this)">
                <img src="/images/global/close.svg">
            </div>

            <img src="/images/pop-up/alert.svg" class="popup-img">

            <h1 class="popup-title">Desistir do Teste</h1>

            <p class="popup-description">Tem certeza que deseja desistir do teste? Você não poderá mais realizar este
                teste para este processo seletivo.</p>

            <button class="popup-btn popup-btn-width" onclick="Close(this)">
                Continuar Teste
            </button>

            <button type="button" class="popup-btn-link" onclick="Back(this, '/home')">
                Desistir
            </button>
        </div>
    </div>

    <!--Page user-->
    <form action="/entrevista_candidato_marcar" method="post" id="formulario">
        <div class="container">
            <div class="title">
                <h1 class="title-1">Teste</h1>
            </div>

            <div class="row mb-3">
                <label for="test_Title" class="col-sm-2 form-label form-label-t-test">Título do Teste</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="test_Title" disabled placeholder="">
                </div>
            </div>

            <hr />

            <div class="title">
                <h2 class="title-2">Perguntas</h2>
                <img src="/images/global/info.svg" onclick="Open('popup-info')">
            </div>

            <div class="questions" id="questions">
                <div id="question_1">
                    <div class="title">
                        <h2 class="title-2">1. <img src="/images/global/edit.svg" alt="edit"></h2>
                    </div>

                    <div class="row mb-3">
                        <label class="form-label">Título da Pergunta</label>
                        <div class="col-sm-12 mb-3">
                            <textarea type="text" class="form-control text-area" name="question_title_1" disabled
                                placeholder=""></textarea>
                        </div>
                    </div>

                    <div class="title">
                        <h2 class="title-2">Respostas</h2>
                    </div>

                    <div>
                        <div class="d-flex align-items-baseline">
                            <input class="check" type="radio" name="radio_question_1" value="">
                            <textarea type="text" class="form-control text-area" disabled placeholder=""></textarea>
                        </div>
                    </div>
                    <div>
                        <div class="d-flex align-items-baseline">
                            <input class="check" type="radio" name="radio_question_1" value="">
                            <textarea type="text" class="form-control text-area" disabled placeholder=""></textarea>
                        </div>
                    </div>
                    <div>
                        <div class="d-flex align-items-baseline">
                            <input class="check" type="radio" name="radio_question_1" value="">
                            <textarea type="text" class="form-control text-area" disabled placeholder=""></textarea>
                        </div>
                    </div>
                    <div>
                        <div class="d-flex align-items-baseline">
                            <input class="check" type="radio" name="radio_question_1" value="">
                            <textarea type="text" class="form-control text-area" disabled placeholder=""></textarea>
                        </div>
                    </div>
                </div>
            </div>

            <div class="buttons buttons-test">
                <button type="button" class="btn btn-outline-primary mb-5"
                    onclick="Open('popup-desistir')">Desistir</button>
                <button type="button" class="btn btn-outline-primary mb-5"
                    onclick="Open('popup-confirm')">Finalizar</button>
            </div>
        </div>
    </form>

    <!--Footer-->
    <footer class="footer">
        <img src="/images/global/linkedin.svg" class="img-footer" onclick="">
        <img src="/images/global/facebook.svg" class="img-footer" onclick="">
        <img src="/images/global/email.svg" class="img-footer" onclick="">
        <label class="label-footer">+55 (15) 5555-5555</label>
    </footer>

    <!--Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ"
        crossorigin="anonymous"></script>

    <script src="/scripts/general-scripts/pop-up.js"></script>
</body>

</html>