<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap / CSS -->
    <link rel="stylesheet" href="/styles/custom-vagas-candidatadas.css">
    <link rel="stylesheet" href="/styles/pop-up.css">

    <title>Vagas Candidatadas</title>
</head>

<body>
    <!--Header-->
    <nav class="navbar navbar-expand-lg navbar-dark" id="header">
        <div class="container-fluid background-navbar">
            <a class="navbar-brand" href="#"><img src="/images/global/logo.svg" alt=""></a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">
                <img src="/images/global/navbar-button.svg" class="navbar-button">
            </button>

            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" aria-current="page" href="/">Home</a>
                    <a class="nav-link active" href="/perfil_ver">Perfil</a>
                    <a class="nav-link" href="/#sobre_nos">Sobre</a>
                    <a class="nav-link" href="/#quem_somos">Quem Somos</a>
                    <a class="nav-link" href="/#nossa_equipe">Nossos Líderes</a>
                    <a class="nav-link" href="/#vagas_abertas">Trabalhe Conosco</a>
                    <a class="nav-link" href="/#contate_nos">Contato</a>
                    <a class="nav-link" href="/usuario_sair">Sair</a>
                </div>
            </div>
        </div>
    </nav>

    <div class="popup-container" id="popup-info">
        <!--onclick="Open('popup-info')"-->
        <!--<link rel="stylesheet" href="../../../../Public/styles/pop-up.css">-->
        <!--<script src="../../../../Public/scripts/general-scripts/pop-up.js"></script>-->
        <div class="popup-content">
            <div class="popup-close" title="Close" onclick="Close(this)">
                <img src="/images/global/close.svg">
            </div>

            <img src="/images/pop-up/info.svg" class="popup-img">

            <h1 class="popup-title">Vagas Candidatadas</h1>

            <p class="popup-description">Aqui aparecerá seu status no processo seletivo ao qual você se candidatou.
                Abaixo de cada etapa você poderá ver um dos três ícones: seta circular azul(em espera); seta check
                roxa(passou de
                etapa); x vermelho(não passou de etapa). O teste pode ser realizado apenas uma vez, então separe um
                tempo para poder iniciar. Caso tenha alguma dúvida entre em contato com a gente na aba "contato" do
                menu.</p>

            <button type="button" class="popup-btn popup-btn-width" onclick="Close(this)">
                Entendi!
            </button>
        </div>
    </div>

    <!--Page user-->
    <form action="requisitante.php" method="post" id="formulario">
        <div class="container">

            <!--parte de cima do perfil-->
            <div class="row d-flex justify-content-center perfil-box">

                <div class="row row-img-names">
                    <div class="img-perfil"></div>

                    <div class="names">
                        <h1 class="nome-perfil">Nome Perfil</h1>
                        <h2 class="nome-usuario">nome_usuario</h2>
                    </div>
                </div>

                <p class="mb-3 descricao-perfil">
                    Aqui fica a descrição do perfil personalizada, diga-nos um pouco
                    sobre você. Aqui fica a sua descrição do perfil personalizada, diga-nos um pouco
                    sobre você. Aqui fica a sua descrição do perfil personalizada, diga-nos um pouco
                    sobre você.
                </p>

                <div class="buttons">
                    <a href="/editar_perfil">
                        <button type="button" class="btn btn-outline-primary mb-2">Editar Perfil</button>
                    </a>
                    <button type="button" class="btn btn-outline-primary mb-2 select">Vagas Candidatadas</button>
                </div>
            </div>

            <hr>

            <!--parte de baixo do perfil-->
            <img src="/images/global/info.svg" class="instructions" onclick="Open('popup-info')">

            <!--Animated bars-->
            <div class="row mb-3 vagas">
                <!--6%-->
                <div class="mb-3 vaga" id="1-etapa">
                    <div class="title">
                        <h2 class="title-2">Engenheiro Elétrico Júnior</h2>
                    </div>

                    <div class="vaga-bar">
                        <div class="vaga-per-6" per="6%"></div>
                    </div>

                    <div class="mb-3 texts">
                        <div class="text-box">
                            <span>Upload <br> do <br> Currículo</span>
                            <img src="/images/custom-perfil/load.svg">
                        </div>

                        <div class="text-box">
                            <span>Teste <br> já <br> Liberado</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Teste <br> já <br> Realizado</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Entrevista <br> já <br> Marcada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Entrevista <br> já <br> Realizada</span>
                            <img src="">
                        </div>
                    </div>

                    <div class="row buttons-bar">
                        <button type="button" class="btn btn-outline-primary mb-2" disabled>Realizar Teste</button>
                        <button type="button" class="btn btn-outline-primary mb-2" disabled>Resultado</button>
                    </div>
                </div>

                <!--28%-->
                <div class="mb-3 vaga" id="2-etapa">
                    <div class="title">
                        <h2 class="title-2">Engenheiro Elétrico Júnior</h2>
                    </div>

                    <div class="vaga-bar">
                        <div class="vaga-per-24" per="28%"></div>
                    </div>

                    <div class="mb-3 texts">
                        <div class="text-box">
                            <span>Upload <br> do <br> Currículo</span>
                            <img src="/images/custom-perfil/checked.svg">
                        </div>

                        <div class="text-box">
                            <span>Teste <br> já <br> Liberado</span>
                            <img src="/images/custom-perfil/wrong.svg">
                        </div>

                        <div class="text-box">
                            <span>Teste <br> já <br> Realizado</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Entrevista <br> já <br> Marcada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Entrevista <br> já <br> Realizada</span>
                            <img src="">
                        </div>
                    </div>

                    <div class="row buttons-bar">
                        <button type="button" class="btn btn-outline-primary mb-2" disabled>Realizar Teste</button>
                        <button type="button" class="btn btn-outline-primary mb-2" disabled>Resultado</button>
                    </div>
                </div>

                <!--50%-->
                <div class="mb-3 vaga" id="3-etapa">
                    <div class="title">
                        <h2 class="title-2">Engenheiro Elétrico Júnior</h2>
                    </div>

                    <div class="vaga-bar">
                        <div class="vaga-per-41" per="50%"></div>
                    </div>

                    <div class="mb-3 texts">
                        <div class="text-box">
                            <span>Upload <br> do <br> Currículo</span>
                            <img src="/images/custom-perfil/checked.svg">
                        </div>

                        <div class="text-box">
                            <span>Teste <br> já <br> Liberado</span>
                            <img src="/images/custom-perfil/checked.svg">
                        </div>

                        <div class="text-box">
                            <span>Teste <br> já <br> Realizado</span>
                            <img src="/images/custom-perfil/load.svg">
                        </div>

                        <div class="text-box">
                            <span>Entrevista <br> já <br> Marcada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Entrevista <br> já <br> Realizada</span>
                            <img src="">
                        </div>
                    </div>

                    <div class="row buttons-bar">
                        <button type="button" class="btn btn-outline-primary mb-2">Realizar Teste</button>
                        <button type="button" class="btn btn-outline-primary mb-2" disabled>Resultado</button>
                    </div>
                </div>

                <!--72%-->
                <div class="mb-3 vaga" id="4-etapa">
                    <div class="title">
                        <h2 class="title-2">Engenheiro Elétrico Júnior</h2>
                    </div>

                    <div class="vaga-bar">
                        <div class="vaga-per-59" per="72%"></div>
                    </div>

                    <div class="mb-3 texts">
                        <div class="text-box">
                            <span>Upload <br> do <br> Currículo</span>
                            <img src="/images/custom-perfil/checked.svg">
                        </div>

                        <div class="text-box">
                            <span>Teste <br> já <br> Liberado</span>
                            <img src="/images/custom-perfil/checked.svg">
                        </div>

                        <div class="text-box">
                            <span>Teste <br> já <br> Realizado</span>
                            <img src="/images/custom-perfil/checked.svg">
                        </div>

                        <div class="text-box">
                            <span>Entrevista <br> já <br> Marcada</span>
                            <img src="/images/custom-perfil/load.svg">
                        </div>

                        <div class="text-box">
                            <span>Entrevista <br> já <br> Realizada</span>
                            <img src="">
                        </div>
                    </div>

                    <div class="row buttons-bar">
                        <button type="button" class="btn btn-outline-primary mb-2" disabled>Realizar Teste</button>
                        <button type="button" class="btn btn-outline-primary mb-2">Resultado</button>
                    </div>
                </div>

                <!--100%-->
                <div class="vaga" id="5-etapa">
                    <div class="title">
                        <h2 class="title-2">Engenheiro Elétrico Júnior</h2>
                    </div>

                    <div class="vaga-bar">
                        <div class="vaga-per-77" per="100%"></div>
                    </div>

                    <div class="mb-3 texts">
                        <div class="text-box">
                            <span>Upload <br> do <br> Currículo</span>
                            <img src="/images/custom-perfil/checked.svg">
                        </div>

                        <div class="text-box">
                            <span>Teste <br> já <br> Liberado</span>
                            <img src="/images/custom-perfil/checked.svg">
                        </div>

                        <div class="text-box">
                            <span>Teste <br> já <br> Realizado</span>
                            <img src="/images/custom-perfil/checked.svg">
                        </div>

                        <div class="text-box">
                            <span>Entrevista <br> já <br> Marcada</span>
                            <img src="/images/custom-perfil/checked.svg">
                        </div>

                        <div class="text-box">
                            <span>Entrevista <br> já <br> Realizada</span>
                            <img src="/images/custom-perfil/load.svg">
                        </div>
                    </div>

                    <div class="row buttons-bar">
                        <button type="button" class="btn btn-outline-primary mb-2" disabled>Realizar Teste</button>
                        <button type="button" class="btn btn-outline-primary mb-2">Resultado</button>
                    </div>
                </div>
            </div>

            <div class="buttons">
                <a href="/perfil_ver">
                    <button type="button" class="btn btn-outline-primary mb-5">Voltar</button>
                </a>
            </div>
        </div>
    </form>

    <!--Footer-->
    <footer class="footer">
        <img src="/images/global/linkedin.svg" class="img-footer" onclick="">
        <img src="/images/global/facebook.svg" class="img-footer" onclick="">
        <img src="/images/global/email.svg" class="img-footer" onclick="">
        <label class="label-footer">+55 (15) 5555-5555</label>
    </footer>

    <!--Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous">
    </script>

    <script src="/scripts/manager-scripts/gerar-requisicao-de-vaga.js"></script>
    <script src="/scripts/general-scripts/pop-up.js"></script>
</body>

</html>