<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Atribuir Teste</title>

    <!-- Bootstrap / CSS -->
    <link rel="stylesheet" href="/styles/custom-atribuir-realizar-teste.css">
    <link rel="stylesheet" href="/styles/pop-up.css">

</head>

<body>
    <!--Header-->
    <nav class="navbar navbar-expand-lg navbar-dark" id="header">
        <div class="container-fluid background-navbar">

            <a class="navbar-brand" href="#"><img src="/images/global/logo.svg" alt=""></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">
                <img src="/images/global/navbar-button.svg" class="navbar-button">
            </button>

            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" href="/home">Home</a>
                    <a class="nav-link" href="">Funcionário</a>
                    <a class="nav-link" href="/gerenciar_candidato">Candidatos</a>
                    <a class="nav-link" href="/gerenciar_vaga">Vagas</a>
                    <a class="nav-link active" href="/gerenciar_processo_seletivo">Processos Seletivos</a>
                    <a class="nav-link" href="/gerenciar_entrevista_candidato">Entrevistas</a>
                    <a class="nav-link" href="/gerar_relatorio">Relatórios</a>
                    <a class="nav-link" href="/usuario_sair">Sair</a>
                </div>
            </div>
        </div>
    </nav>

    <!--Pop-up area-->
    <div class="popup-container" id="popup-info">
        <!--onclick="Open('popup-info')"-->
        <!--<link rel="stylesheet" href="../../../../Public/styles/pop-up.css">-->
        <!--<script src="../../../../Public/scripts/general-scripts/pop-up.js"></script>-->
        <div class="popup-content">
            <div class="popup-close" title="Close" onclick="Close(this)">
                <img src="/images/global/close.svg">
            </div>

            <img src="/images/pop-up/info.svg" class="popup-img">

            <h1 class="popup-title">Atribuir Teste</h1>

            <p class="popup-description">Você pode criar quantas perguntas desejar, porém com apenas uma resposta certa
                para cada questão. </p>

            <button type="button" class="popup-btn popup-btn-width" onclick="Close(this)">
                Entendi!
            </button>
        </div>
    </div>

    <div class="popup-container" id="popup-confirm">
        <!--onclick="Open('popup-confirm')"-->
        <!--<link rel="stylesheet" href="../../../../Public/styles/pop-up.css">-->
        <!--<script src="../../../../Public/scripts/general-scripts/pop-up.js"></script>-->
        <div class="popup-content">
            <div class="popup-close" title="Close">
                <img src="/images/global/close.svg" onclick="Close(this)">
            </div>

            <img src="/images/pop-up/alert.svg" class="popup-img">

            <h1 class="popup-title">Atribuir Teste</h1>

            <p class="popup-description">Tem certeza que deseja atribuir o teste? Após atribuido, você não poderá mais
                editar suas perguntas.</p>

            <button class="popup-btn popup-btn-width" onclick="Confirm(this)">
                Confirmar
            </button>

            <button type="button" class="popup-btn-link" onclick="Close(this)">
                Voltar
            </button>
        </div>
    </div>

    <div class="popup-container" id="popup-back">
        <!--onclick="Open('popup-back')"-->
        <!--<link rel="stylesheet" href="../../../../Public/styles/pop-up.css">-->
        <!--<script src="../../../../Public/scripts/general-scripts/pop-up.js"></script>-->
        <div class="popup-content">
            <div class="popup-close" title="Close">
                <img src="/images/global/close.svg" onclick="Close(this)">
            </div>

            <img src="/images/pop-up/alert.svg" class="popup-img">

            <h1 class="popup-title">Cancelar Atribuição</h1>

            <p class="popup-description">Tem certeza que deseja cancelar a atribuição? Após voltar para a tela
                anterior, todas as perguntas e respostas inseridas serão perdidas.</p>

            <button class="popup-btn popup-btn-width" onclick="Back(this, '/gerenciar_processo_seletivo')">
                Confirmar
            </button>

            <button type="button" class="popup-btn-link" onclick="Close(this)">
                Voltar
            </button>
        </div>
    </div>

    <!--Page user-->
    <form action="/cadastrar_teste" method="post" id="formulario">
        <div class="container">
            <div class="title">
                <h1 class="title-1 mb-4">Atribuir Teste</h1>
            </div>

            <div class="row mb-3">
                <label for="test_Title" class="col-sm-2 form-label form-label-t-test">Título do Teste</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control digitar-titulo" name="test_Title">
                </div>
            </div>

            <div class="row mb-3">
                <label for="description" class="form-label">Descrição</label>
                <div class="col-sm-12 mb-3">
                    <textarea type="text" class="form-control text-area" name="description"></textarea>
                </div>
            </div>

            <hr />

            <div class="title">
                <h2 class="title-2">Perguntas</h2>
                <!-- <img src="../../../../Public/images/global/info.svg"> -->
                <img src="/images/global/info.svg" onclick="Open('popup-info')">
            </div>

            <div class="questions" id="questions">
                <div id="question_1">
                    <div class="title">
                        <h2 class="title-2">1. <img src="/images/global/edit.svg" alt="edit"></h2>
                    </div>

                    <div class="row mb-3">
                        <label class="form-label">Título da Pergunta</label>
                        <div class="col-sm-12">
                            <textarea type="text" class="form-control text-area titulo"
                                name="question_title_1"></textarea>
                        </div>
                    </div>

                    <div class="title">
                        <h2 class="title-2">Respostas</h2>
                    </div>

                    <div class="mb-3">
                        <label class="letra">A)</label>
                        <textarea type="text" class="form-control text-area" name="quest_1_answer_1"></textarea>
                        <label>Resposta Correta:</label>
                        <label class="switch">
                            <input type="checkbox" name="check_quest_1_answer_1">
                            <span class="slider round"></span>
                        </label>
                    </div>

                    <div class="mb-3">
                        <label class="letra">B)</label>
                        <textarea type="text" class="form-control text-area" name="quest_1_answer_2"></textarea>
                        <label>Resposta Correta: </label>
                        <label class="switch">
                            <input type="checkbox" name="check_quest_1_answer_2">
                            <span class="slider round"></span>
                        </label>
                    </div>

                    <div class="mb-3">
                        <label class="letra">C)</label>
                        <textarea type="text" class="form-control text-area" name="quest_1_answer_3"></textarea>
                        <label>Resposta Correta: </label>
                        <label class="switch">
                            <input type="checkbox" name="check_quest_1_answer_3">
                            <span class="slider round"></span>
                        </label>
                    </div>

                    <div class="mb-3">
                        <label class="letra">D)</label>
                        <textarea type="text" class="form-control text-area" name="quest_1_answer_4"></textarea>
                        <label>Resposta Correta: </label>
                        <label class="switch">
                            <input type="checkbox" name="check_quest_1_answer_4">
                            <span class="slider round"></span>
                        </label>
                    </div>
                </div>
                <div id="btn-area-form-0" class="btn-area-form">
                    <img src="/images/custom-requisicao-de-vaga/plus.svg" class="btn-form" onclick="addPergunta()">
                    <img src="/images/custom-requisicao-de-vaga/minus.svg" class="btn-form" onclick="removePergunta()">
                </div>
            </div>
            <input type="hidden" name="id_proc" value="<?= $this->view->detalhesProcessoSeletivo->id_proc ?>" readonly>
            <div class="buttons">
                <a class="btn btn-outline-primary mb-5" onclick="Open('popup-back')">Voltar</a>
                <button type="button" class="btn btn-outline-primary mb-5"
                    onclick="Open('popup-confirm')">Atribuir</button>
            </div>
            <!--  -->
        </div>
    </form>

    <!--Footer-->
    <footer class="footer">
        <img src="/images/global/linkedin.svg" class="img-footer" onclick="">
        <img src="/images/global/facebook.svg" class="img-footer" onclick="">
        <img src="/images/global/email.svg" class="img-footer" onclick="">
        <label class="label-footer">+55 (15) 5555-5555</label>
    </footer>

    <!--Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous">
    </script>

    <!-- <script src="../../../../Public/scripts/employee-scripts/atribuir-teste.js"></script> -->
    <script src="/scripts/employee-scripts/atribuir-teste.js"></script>
    <script src="/scripts/general-scripts/pop-up.js"></script>
</body>

</html>