<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Marcar Entrevista</title>

    <!-- Bootstrap / CSS -->
    <link rel="stylesheet" href="/styles/custom-marcar-entrevista.css">
    <link rel="stylesheet" href="/styles/pop-up.css">

</head>

<body>

    <!--Header-->
    <nav class="navbar navbar-expand-lg navbar-dark" id="header">
        <div class="container-fluid background-navbar">
            <a class="navbar-brand" href="/home"><img src="/images/global/logo.svg" alt=""></a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">
                <img src="/images/global/navbar-button.svg" class="navbar-button">
            </button>

            <?php if($_SESSION['tipo_user'] == 2) { ?>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" href="/home">Home</a>
                        <a class="nav-link" href="">Funcionário</a>
                        <a class="nav-link" href="/gerenciar_candidato">Candidatos</a>
                        <a class="nav-link" href="/gerenciar_vaga">Vagas</a>
                        <a class="nav-link" href="/gerenciar_processo_seletivo">Processos Seletivos</a>
                        <a class="nav-link active" href="/gerenciar_entrevista_candidato">Entrevistas</a>
                        <a class="nav-link" href="/gerar_relatorio">Relatórios</a>
                        <a class="nav-link" href="/usuario_sair">Sair</a>
                    </div>
                </div>
            <?php } elseif($_SESSION['tipo_user'] == 3){ ?>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" href="/home">Home</a>
                        <a class="nav-link" href="">Gestor</a>
                        <a class="nav-link" href="/requisicoes_vaga">Requisições</a>
                        <a class="nav-link" href="/gerenciar_processo_seletivo">Processos Seletivos</a>
                        <a class="nav-link active" href="/gerenciar_entrevista_candidato">Entrevistas</a>
                        <a class="nav-link" href="/usuario_sair">Sair</a>               
                    </div>
                </div>
            <?php } elseif($_SESSION['tipo_user'] == 4){ ?>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" href="/home">Home</a>
                        <a class="nav-link" href="">Líder</a>
                        <a class="nav-link" href="/requisicoes_vaga">Requisições</a>
                        <a class="nav-link" href="/gerenciar_processo_seletivo">Processos Seletivos</a>
                        <a class="nav-link active" href="/gerenciar_entrevista_candidato">Entrevistas</a>
                        <a class="nav-link" href="/usuario_sair">Sair</a>               
                    </div>
                </div>
            <?php } else { ?>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" href="/home">Home</a>
                        <a class="nav-link" href="">Admin</a>
                        <a class="nav-link" href="/gerenciar_candidato">Candidatos</a>
                        <a class="nav-link" href="/requisicoes_vaga">Requisições</a>
                        <a class="nav-link" href="/gerenciar_vaga">Vagas</a>
                        <a class="nav-link" href="/gerenciar_processo_seletivo">Processos Seletivos</a>
                        <a class="nav-link active" href="/gerenciar_entrevista_candidato">Entrevistas</a>
                        <a class="nav-link" href="/gerar_relatorio">Relatórios</a>
                        <a class="nav-link" href="/usuario_sair">Sair</a>
                    </div>
                </div>
             <?php } ?>
        </div>
    </nav>

    <div class="popup-container" id="popup-confirm">
        <!--onclick="Open('popup-confirm')"-->
        <!--<link rel="stylesheet" href="../../../../Public/styles/pop-up.css">-->
        <!--<script src="../../../../Public/scripts/general-scripts/pop-up.js"></script>-->
        <div class="popup-content">
            <div class="popup-close" title="Close">
                <img src="/images/global/close.svg" onclick="Close(this)">
            </div>

            <img src="/images/pop-up/alert.svg" class="popup-img">

            <h1 class="popup-title">Marcar Entrevista</h1>

            <p class="popup-description">Tem certeza que deseja marcar essa entrevista?</p>

            <button class="popup-btn popup-btn-width" onclick="Confirm(this, '/entrevista_candidato_marcar')">
                Confirmar
            </button>

            <button type="button" class="popup-btn-link" onclick="Close(this)">
                Voltar
            </button>
        </div>
    </div>

    <div class="popup-container" id="popup-back">
        <!--onclick="Open('popup-back')"-->
        <!--<link rel="stylesheet" href="../../../../Public/styles/pop-up.css">-->
        <!--<script src="../../../../Public/scripts/general-scripts/pop-up.js"></script>-->
        <div class="popup-content">
            <div class="popup-close" title="Close">
                <img src="/images/global/close.svg" onclick="Close(this)">
            </div>

            <img src="/images/pop-up/alert.svg" class="popup-img">

            <h1 class="popup-title">Voltar</h1>

            <p class="popup-description">Tem certeza que deseja cancelar a entrevista? Todas as informações inseridas
                serão perdidas.</p>

            <button class="popup-btn popup-btn-width" onclick="Back(this, '/gerenciar_entrevista_candidato')">
                Confirmar
            </button>

            <button type="button" class="popup-btn-link" onclick="Close(this)">
                Voltar
            </button>
        </div>
    </div>

    <div class="popup-container" id="popup-back">
        <!--onclick="Open('popup-back')"-->
        <!--<link rel="stylesheet" href="../../../../Public/styles/pop-up.css">-->
        <!--<script src="../../../../Public/scripts/general-scripts/pop-up.js"></script>-->
        <div class="popup-content">
            <div class="popup-close" title="Close">
                <img src="/images/global/close.svg" onclick="Close(this)">
            </div>

            <img src="/images/pop-up/alert.svg" class="popup-img">

            <h1 class="popup-title">Cancelar Marcação</h1>

            <p class="popup-description">Tem certeza que deseja voltar para a página anterior? Todas as informações
                inseridas
                serão perdidas.</p>

            <button class="popup-btn popup-btn-width" onclick="Back(this, 'gerenciar_entrevista_candidato')">
                Confirmar
            </button>

            <button type="button" class="popup-btn-link" onclick="Close(this)">
                Voltar
            </button>
        </div>
    </div>

    <!--Page user-->
    <form action="/entrevista_candidato_marcar" method="post" id="formulario">
        <div class="container">
            <div class="title">
                <h1 class="title-1">Marcar Entrevista</h1>
            </div>

            <!--Pesquisa-->
            <div class="row">
                <label class="label1">Título</label>

                <input type="text" class="form-control" name="titulo" required>
            </div>

            <div class="row">
                <label class="label1">Descrição</label>

                <textarea type="text" class="form-control" id="textarea" rows="3" name="desc" required></textarea>
            </div>

            <div class="row">
                <label for="sdate" class="label1">Data</label>

                <input type="date" class="form-control" name="date" required>
            </div>

            <div class="row">
                <label for="hora" class="label1">Hora</label>

                <input type="time" class="form-control" name="hora" required>
            </div>

            <div class="row">
                <label class="label2">Processo Seletivo</label>

                <select class="form-select" aria-label="processo-seletivo" name="processo-seletivo" required>
                    <option selected></option>
                    <option value="1">#</option>
                    <option value="2">#</option>
                    <option value="3">#</option>
                </select>
            </div>

            <div class="row">
                <label class="label2">Candidato</label>

                <select class="form-select" aria-label="nome-candidato" name="nome-candidato" required>
                    <option selected></option>
                    <option value="1">#</option>
                    <option value="2">#</option>
                    <option value="3">#</option>
                </select>
            </div>

            <div class="row">
                <label class="label2">Responsável</label>

                <select class="form-select" aria-label="resp" name="resp" required>
                    <option selected></option>
                    <option value="1">#</option>
                    <option value="2">#</option>
                    <option value="3">#</option>
                </select>
            </div>

            <hr>

            <div class="buttons">
                <!-- <button type="button" class="btn btn-outline-primary mb-5 accept">Salvar</button>
                <button type="button" class="btn btn-outline-primary mb-5 delete">Excluir</button> -->
                <button type="button" class="btn btn-outline-primary mb-5" onclick="Open('popup-back')">Voltar</button>
                <button type="button" class="btn btn-outline-primary mb-5"
                    onclick="Open('popup-confirm')">Marcar</button>
            </div>
        </div>
    </form>

    <!--Footer-->
    <footer class="footer">
        <img src="/images/global/linkedin.svg" class="img-footer" onclick="">
        <img src="/images/global/facebook.svg" class="img-footer" onclick="">
        <img src="/images/global/email.svg" class="img-footer" onclick="">
        <label class="label-footer">+55 (15) 5555-5555</label>
    </footer>


    <!--Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous">
    </script>

    <script src="/scripts/manager-scripts/marcar-entrevista.js"></script>
    <script src="/scripts/general-scripts/pop-up.js"></script>
</body>

</html>