<!doctype html>
<html lang="pt-BR">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap / CSS -->
    <link rel="stylesheet" href="styles/custom-gerar-relatorio.css">

    <title>Gerar Relatórios</title>
</head>

<body>
    <!--Header-->
    <nav class="navbar navbar-expand-lg navbar-dark" id="header">
        <div class="container-fluid background-navbar">
            <a class="navbar-brand" href="/home"><img src="/images/global/logo.svg" alt=""></a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">
                <img src="/images/global/navbar-button.svg" class="navbar-button">
            </button>

            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" href="/home">Home</a>
                    <a class="nav-link" href="/#">Funcionário</a>
                    <a class="nav-link" href="/gerenciar_candidato">Candidatos</a>
                    <a class="nav-link" href="/requisicoes_vaga">Requisições</a>
                    <a class="nav-link" href="/gerenciar_vaga">Vagas</a>
                    <a class="nav-link" href="/gerenciar_processo_seletivo">Processos Seletivos</a>
                    <a class="nav-link" href="/teste_candidato">Testes</a>
                    <a class="nav-link" href="/entrevista_candidato">Entrevistas</a>
                    <a class="nav-link" href="/gerar_relatorio">Relatórios</a>
                    <a class="nav-link" href="/usuario_sair">Sair</a>
                </div>
            </div>
        </div>
    </nav>

    <!--Body-->
    <div class="container" id="body">

        <div class="title">
            <h1 class="title-1">Relatórios Disponíveis</h1>
        </div>

        <div class="row relatorio mb-2">
            <div class="col text-relatorio-area">
                <h3 class="title-2">Indicadores de Desempenho</h3>

                <div class="row description">
                    <img src="/images/custom-gerar-relatorio/Gráfico.png" alt="" class="relatorio-img">

                    <p class="text-relatorio">
                        Este relatório mostra as estatísticas dos processos seletivos da empresa em um determinado
                        período de tempo.
                    </p>
                </div>
            </div>

            <div class="btn-relatorio">
                <a href="/gerar_relatorio_indicadores_desempenho"><button type="button"
                        class="col btn btn-outline-primary mb-2 btn-view">Visualizar</button></a>
            </div>
        </div>

        <div class="row relatorio mb-2">
            <div class="col text-relatorio-area">
                <h3 class="title-2">Recrutamento e Seleção</h3>

                <div class="row description">
                    <img src="/images/custom-gerar-relatorio/Pessoas.png" alt="" class="relatorio-img">

                    <p class="text-relatorio">
                        Este relatório mostra os dados de todos os candidatos associados a cada vaga cadastrada no
                        sistema.
                    </p>
                </div>
            </div>

            <div class="btn-relatorio">
                <a href="/gerar_relatorio_recrutamento_selecao"><button type="button"
                        class="col btn btn-outline-primary mb-2 btn-view">Visualizar</button></a>
            </div>
        </div>

        <div class="row relatorio">
            <div class="col text-relatorio-area">
                <h3 class="title-2">Quadro de Vagas</h3>

                <div class="row description">
                    <img src="/images/custom-gerar-relatorio/Prancheta.png" alt="" class="relatorio-img">

                    <p class="text-relatorio">
                        Este relatório mostra os dados de todas as vagas cadastradas, assim como as vagas que entraram e
                        saíram do sistema em um determinado período de tempo.
                    </p>
                </div>
            </div>

            <div class="btn-relatorio">
                <a href="/gerar_relatorio_quadro_vagas"><button type="button"
                        class="col btn btn-outline-primary mb-2 btn-view">Visualizar</button></a>
            </div>
        </div>

        <div class="buttons">
            <button type="button" class="btn btn-outline-primary mb-5"
                onclick="window.location.href = '/home'">Voltar</button>
        </div>
    </div>

    <!--Footer-->
    <footer class="footer">
        <img src="/images/global/linkedin.svg" class="img-footer" onclick="">
        <img src="/images/global/facebook.svg" class="img-footer" onclick="">
        <img src="/images/global/email.svg" class="img-footer" onclick="">
        <label class="label-footer">+55 (15) 5555-5555</label>
    </footer>

    <!--Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous">
    </script>

</body>

</html>