<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gerenciar Processo Seletivo</title>

    <!-- Bootstrap / CSS -->
    <link rel="stylesheet" href="/styles/custom-gerenciar-processo-seletivo.css">

    <script type="text/javascript">
        let cargos = <?php echo json_encode($this->view->cargos) ?>;
    </script>

</head>

<body>
    <!--Header-->
    <nav class="navbar navbar-expand-lg navbar-dark" id="header">
        <div class="container-fluid background-navbar">
            <a class="navbar-brand" href="/home"><img src="/images/global/logo.svg" alt=""></a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">
                <img src="/images/global/navbar-button.svg" class="navbar-button">
            </button>

            <?php if($_SESSION['tipo_user'] == 2) { ?>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" href="/home">Home</a>
                        <a class="nav-link" href="">Funcionário</a>
                        <a class="nav-link" href="/gerenciar_candidato">Candidatos</a>
                        <a class="nav-link" href="/gerenciar_vaga">Vagas</a>
                        <a class="nav-link active" href="/gerenciar_processo_seletivo">Processos Seletivos</a>
                        <a class="nav-link" href="/gerenciar_entrevista_candidato">Entrevistas</a>
                        <a class="nav-link" href="/gerar_relatorio">Relatórios</a>
                        <a class="nav-link" href="/usuario_sair">Sair</a>
                    </div>
                </div>
            <?php } elseif($_SESSION['tipo_user'] == 3){ ?>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" href="/home">Home</a>
                        <a class="nav-link" href="">Gestor</a>
                        <a class="nav-link" href="/requisicoes_vaga">Requisições</a>
                        <a class="nav-link active" href="/gerenciar_processo_seletivo">Processos Seletivos</a>
                        <a class="nav-link" href="/gerenciar_entrevista_candidato">Entrevistas</a>
                        <a class="nav-link" href="/usuario_sair">Sair</a>               
                    </div>
                </div>
            <?php } elseif($_SESSION['tipo_user'] == 4){ ?>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" href="/home">Home</a>
                        <a class="nav-link" href="">Líder</a>
                        <a class="nav-link" href="/requisicoes_vaga">Requisições</a>
                        <a class="nav-link active" href="/gerenciar_processo_seletivo">Processos Seletivos</a>
                        <a class="nav-link" href="/gerenciar_entrevista_candidato">Entrevistas</a>
                        <a class="nav-link" href="/usuario_sair">Sair</a>               
                    </div>
                </div>
            <?php } else { ?>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" href="/home">Home</a>
                        <a class="nav-link" href="">Admin</a>
                        <a class="nav-link" href="/gerenciar_candidato">Candidatos</a>
                        <a class="nav-link" href="/requisicoes_vaga">Requisições</a>
                        <a class="nav-link" href="/gerenciar_vaga">Vagas</a>
                        <a class="nav-link active" href="/gerenciar_processo_seletivo">Processos Seletivos</a>
                        <a class="nav-link" href="/gerenciar_entrevista_candidato">Entrevistas</a>
                        <a class="nav-link" href="/gerar_relatorio">Relatórios</a>
                        <a class="nav-link" href="/usuario_sair">Sair</a>
                    </div>
                </div>
             <?php } ?>

        </div>
    </nav>

    <div class="container">
        <div class="title">
            <h1 class="title-1">Gerenciar Processos Seletivos</h1>
        </div>

        <!--Pesquisa-->
        <div class="row mb-3">
            <label for="colFormLabel" class="col-sm-2 form-label">Departamento</label>
            <div class="col-sm-10">
                <select class="col form-select form1" name="departamento" onchange="atribuitDept(this)">
                    <option selected>Todos</option>
                    <?php foreach ($this->view->departamentos as $key => $departamento) { ?>
                    <option value="<?=$departamento->id_departamento?>">
                        <?= $departamento->nome_departamento ?>
                    </option>
                    <?php } ?>
                </select>
            </div>
        </div>

        <div class="row mb-3">
            <label for="colFormLabel" class="col-sm-2 form-label">Cargo</label>
            <div class="col-sm-10">
                <select class="col form-select form1" name="cargo">
                    <option selected>Todos</option>
                    <?php foreach ($this->view->cargos as $key => $cargo) { ?>
                    <option value="<?=$cargo->id_cargo?>">
                        <?= $cargo->nome_cargo ?>
                    </option>
                    <?php } ?>
                </select>
            </div>
        </div>

        <div class="row mb-3">
            <label for="colFormLabel" class="col-sm-2 form-label">Organizar por</label>

            <select class="col-sm-10 form-select" aria-label="organizar-por" name="organizar-por">
                <option selected>Todos</option>
                <option value="1">Mais recente</option>
                <option value="2">Menos recente</option>
            </select>
        </div>

        <hr>

        <?php if($_SESSION['tipo_user'] == 2 || $_SESSION['tipo_user'] == 5){ ?>
        <?php foreach($this->view->todosProcessoSeletivos as $key => $processoSeletivo) {?>
        <form action="/visualizar_processo_seletivo" method="post">
            <div class="depto-recursos-humanos">
                <div class="card">
                    <div class="card-img"></div>

                    <div class="card-body">
                        <h4 class="card-title">Departamento: RH - Recrutamento e Seleção
                            <!-- $processoSeletivo->nome_departamento -->
                        </h4>
                        <h6 class="card-text">
                            <?= $processoSeletivo->titulo_proc ?>

                            <span>
                                - <?= $processoSeletivo->data_inicio ?>
                            </span>

                            <span>
                                à <?= $processoSeletivo->data_termino ?>
                            </span>

                            <span>
                                - <?= $processoSeletivo->status_proc?>
                            </span>
                        </h6>

                    </div>
                </div>
                <!-- <button type="button" class="btn btn-outline-primary mb-4">Divulgar</button> -->
                <button type="submit" class="btn btn-outline-primary mb-4">Visualizar</button>
                <input type="hidden" name="id_proc" value="<?= $processoSeletivo->id_proc ?>">
            </div>
        </form>
            <?php if($processoSeletivo->status_proc != 'Aberto'){ ?>
                <button id="divulgarDis" type="submit" class="btn btn-outline-primary mb-4" disabled>Divulgar</button>     
            <?php } else {?>
                <a href="/divulgar_processo_seletivo?id_proc=<?= $processoSeletivo->id_proc ?>"><button id="divulgar" type="submit" class="btn btn-outline-primary mb-4">Divulgar</button></a> 
            <?php } ?>
        <?php } ?>
        <hr>

        <div id="btnGerenciar" class="buttons">
            <button type="button" class="btn btn-outline-primary mb-5"
                onclick="window.location.href = '/home'">Voltar</button>
            <button id="btnCadastrar" type="button" class="btn btn-outline-primary mb-5"
                onclick="window.location.href = '/processo_seletivo'">Cadastrar</button>
        </div>
        <?php } else { ?>
        <?php foreach($this->view->todosProcessoSeletivos as $key => $processoSeletivo) {?>
        <form action="/visualizar_processo_seletivo" method="post">
            <div class="depto-recursos-humanos">
                <div class="card">
                    <div class="card-img"></div>

                    <div class="card-body">
                        <h4 class="card-title">Departamento: RH - Recrutamento e Seleção
                            <!-- $processoSeletivo->nome_departamento -->
                        </h4>
                        <h6 class="card-text">
                            <?= $processoSeletivo->titulo_proc ?>

                            <span>
                                - <?= $processoSeletivo->data_inicio ?>
                            </span>

                            <span>
                                à <?= $processoSeletivo->data_termino ?>
                            </span>

                            <span>
                                - <?= $processoSeletivo->status_proc ?>
                            </span>
                        </h6>

                    </div>
                </div>

                <button type="submit" class="btn btn-outline-primary mb-4">Visualizar</button>
                <input type="hidden" name="id_proc" value="<?= $processoSeletivo->id_proc ?>">
            </div>
        </form>
        <?php } ?>

        <hr>

        <div id="btnGerenciar" class="buttons">
            <button type="button" class="btn btn-outline-primary mb-5"
                onclick="window.location.href = '/home'">Voltar</button>
        </div>
        <?php } ?>

    </div>

    <!--Footer-->
    <footer class="footer"  style="margin-top: 100vh;">
        <img src="/images/global/linkedin.svg" class="img-footer" onclick="">
        <img src="/images/global/facebook.svg" class="img-footer" onclick="">
        <img src="/images/global/email.svg" class="img-footer" onclick="">
        <label class="label-footer">+55 (15) 5555-5555</label>
    </footer>


    <!--Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous">
    </script>

    <script src="/scripts/manager-scripts/gerar-requisicao-de-vaga.js"></script>
</body>

</html>