<!doctype html>
<html lang="pt-BR">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap / CSS -->
    <link rel="stylesheet" href="/styles/custom-relatorio-quadro-de-vagas.css">

    <title>Relatório de Quadro de Vagas</title>
</head>

<body>

    <!--Header-->
    <nav class="navbar navbar-expand-lg navbar-dark" id="header">
        <div class="container-fluid background-navbar">
            <a class="navbar-brand" href="/home"><img src="/images/global/logo.svg" alt=""></a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">
                <img src="/images/global/navbar-button.svg" class="navbar-button">
            </button>

            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" href="/home">Home</a>
                    <a class="nav-link" href="/#">Funcionário</a>
                    <a class="nav-link" href="/gerenciar_candidato">Candidatos</a>
                    <a class="nav-link" href="/requisicoes_vaga">Requisições</a>
                    <a class="nav-link" href="/gerenciar_vaga">Vagas</a>
                    <a class="nav-link" href="/gerenciar_processo_seletivo">Processos Seletivos</a>
                    <a class="nav-link" href="/teste_candidato">Testes</a>
                    <a class="nav-link" href="/entrevista_candidato">Entrevistas</a>
                    <a class="nav-link" href="/gerar_relatorio">Relatórios</a>
                    <a class="nav-link" href="/usuario_sair">Sair</a>
                </div>
            </div>
        </div>
    </nav>

    <!--Body-->
    <div class="container" id="body">

        <div class="title">
            <h1 class="title-1">Relatório de Quadro de Vagas</h1>
        </div>

        <div class="row mb-2">
            <label for="colFormLabel" class="label">Período</label>
            <div class="row mb-3 info-container">
                <input type="date" class="form-control edit" id="colFormLabel" placeholder="" name="data-de-inicio">

                <span class="span">à</span>

                <input type="date" class="form-control edit" id="colFormLabel" placeholder="" name="data-de-termino">
            </div>
        </div>

        <div class="row mb-2">
            <label for="colFormLabel" class="label">Departamento</label>
            <div class="col-sm-10">
                <select class="col form-select" aria-label="Departamento" name="departamento">
                    <option selected>Todos</option>
                    <option value="1">#</option>
                    <option value="2">#</option>
                    <option value="3">#</option>
                </select>
            </div>
        </div>

        <div class="row mb-2">
            <label for="colFormLabel" class="label">Cargo</label>
            <div class="col-sm-10">
                <select class="col form-select" aria-label="Cargo" name="cargo">
                    <option selected>Todos</option>
                    <option value="1">#</option>
                    <option value="2">#</option>
                    <option value="3">#</option>
                </select>
            </div>
        </div>

        <div class="row mb-3">
            <label for="colFormLabel" class="label">Organizar por</label>
            <select class="col-sm-10 form-select" aria-label="organizar-por" name="organizar-por">
                <option selected>Mais recentes</option>
                <option value="1">Mais antigas</option>
            </select>
        </div>
        <br>


        <h3 class="title-2">Dep. Finanças</h3>
        <p id="Cargo" class="cargo">Cargo: #</p>
        <table class="TB">
            <tr>
                <td class="roxo">Limite de Vagas</td>
                <td class="roxo">Vagas Disponíveis</td>
                <td class="roxo">Qtde. Funcionários</td>
            </tr>
            <tr>
                <td class="cinza" id="TabNum">#</td>
                <td class="cinza" id="TabNum">#</td>
                <td class="cinza" id="TabNum">#</td>
            </tr>
        </table>
        <br><br>

        <h3 class="title-2">Dep. Engenharia Elétrica</h3>
        <p id="Cargo2" class="cargo">Cargo: #</p>
        <table class="TB">
            <tr>
                <td class="roxo">Limite de Vagas</td>
                <td class="roxo">Vagas Disponíveis</td>
                <td class="roxo">Qtde. Funcionários</td>
            </tr>
            <tr>
                <td class="cinza" id="TabNum">#</td>
                <td class="cinza" id="TabNum">#</td>
                <td class="cinza" id="TabNum">#</td>
            </tr>
        </table>
        <br><br>

        <h3 class="title-2">Dep. Recursos Humanos</h3>
        <p id="Cargo3" class="cargo">Cargo: #</p>
        <table class="TB">
            <tr>
                <td class="roxo">Limite de Vagas</td>
                <td class="roxo">Vagas Disponíveis</td>
                <td class="roxo">Qtde. Funcionários</td>
            </tr>
            <tr>
                <td class="cinza" id="TabNum">#</td>
                <td class="cinza" id="TabNum">#</td>
                <td class="cinza" id="TabNum">#</td>
            </tr>
        </table>
        <br><br>

        <div class="buttons">
            <button type="button" class="btn btn-outline-primary mb-5"
                onclick="window.location.href = '/gerar_relatorio'">Voltar</button>
        </div>

    </div>
    </form>

    <!--Footer-->
    <footer class="footer">
        <img src="/images/global/linkedin.svg" class="img-footer" onclick="">
        <img src="/images/global/facebook.svg" class="img-footer" onclick="">
        <img src="/images/global/email.svg" class="img-footer" onclick="">
        <label class="label-footer">+55 (15) 5555-5555</label>
    </footer>

    <!--Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ"
        crossorigin="anonymous"></script>
</body>

</html>