<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap / CSS -->
    <link rel="stylesheet" href="/styles/custom-visualizar-candidato.css">
    <link rel="stylesheet" href="/styles/pop-up.css">

    <title>Visualizar Candidato</title>
</head>

<body>
    <!--Header-->
    <nav class="navbar navbar-expand-lg navbar-dark" id="header">
        <div class="container-fluid background-navbar">
            <a class="navbar-brand" href="#"><img src="/images/global/logo.svg" alt=""></a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">
                <img src="/images/global/navbar-button.svg" class="navbar-button">
            </button>

            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" href="#">Home</a>
                    <a class="nav-link" href="#">Funcionário</a>
                    <a class="nav-link active" href="#">Candidatos</a>
                    <a class="nav-link" href="#">Requisições</a>
                    <a class="nav-link" href="#">Vagas</a>
                    <a class="nav-link" href="#">Processos Seletivos</a>
                    <a class="nav-link" href="#">Testes</a>
                    <a class="nav-link" href="#">Entrevistas</a>
                    <a class="nav-link" href="#">Suporte</a>
                    <a class="nav-link" href="#">Sair</a>
                </div>
            </div>
        </div>
    </nav>

    <!--Pop-up area-->
    <div class="popup-container" id="popup-confirm">
        <!--onclick="Open('popup-confirm')"-->
        <!--<link rel="stylesheet" href="../../../../Public/styles/pop-up.css">-->
        <!--<script src="../../../../Public/scripts/general-scripts/pop-up.js"></script>-->
        <div class="popup-content">
            <div class="popup-close" title="Close">
                <img src="/images/global/close.svg" onclick="Close(this)">
            </div>

            <img src="/images/pop-up/alert.svg" class="popup-img">

            <h1 class="popup-title">Excluir Candidato</h1>

            <p class="popup-description">Tem certeza que deseja excluir este candidato do processo seletivo? Ele não
                poderá mais se candidatar para este processo.</p>

            <button class="popup-btn popup-btn-width" onclick="Confirm(this)">
                Confirmar
            </button>

            <button type="button" class="popup-btn-link" onclick="Close(this)">
                Voltar
            </button>
        </div>
    </div>

    <!--Page user-->
    <form action="requisitante.php" method="post" id="formulario">
        <div class="container">

            <!--parte de cima do perfil-->
            <div class="row d-flex justify-content-center perfil-box">

                <div class="row row-img-names">
                    <div class="img-perfil"></div>

                    <div class="names">
                        <h1 class="nome-perfil">Nome Perfil</h1>
                        <h2 class="nome-usuario">nome_usuario</h2>
                    </div>
                </div>

                <p class="mb-3 descricao-perfil">
                    Aqui fica a descrição do perfil personalizada, diga-nos um pouco
                    sobre você. Aqui fica a sua descrição do perfil personalizada, diga-nos um pouco
                    sobre você. Aqui fica a sua descrição do perfil personalizada, diga-nos um pouco
                    sobre você.
                </p>

                <div class="row buttons">
                    <div class="area-btn">
                        <button type="button" class="col btn btn-outline-primary mb-2">Resultado Teste</button>
                        <button type="button" class="btn btn-outline-primary mb-2">Resultado Entrevista</button>
                    </div>
                </div>
            </div>

            <hr class="mb-4">

            <!--parte de baixo do perfil-->

            <!--dados pessoais-->
            <div class="title">
                <h2 class="title-2">Dados Pessoais</h2>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="colsm-2 form-label">Data de Nascimento</label>
                <div class="col-sm-10">
                    <input type="date" class="form-control" id="colFormLabel" placeholder="07/08/1997"
                        name="data-de-nascimento" readonly>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="colsm-2 form-label">Sexo</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="colFormLabel" placeholder="Masculino" name="sexo"
                        readonly>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">CPF</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="colFormLabel" placeholder="423.123.456-54" name="cpf"
                        readonly>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">CNPJ</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="colFormLabel" placeholder="05.993.943/0001-86"
                        name="cnpj" readonly>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Disponibilidade</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="colFormLabel" placeholder="Sim" name="disponibilidade"
                        readonly>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Status</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="colFormLabel" placeholder="Desempregado" name="status"
                        readonly>
                </div>
            </div>

            <!--contato-->

            <div class="title">
                <h2 class="title-2">Contato</h2>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="colsm-2 form-label">Telefone</label>
                <div class="col-sm-10">
                    <input type="tel" class="form-control" id="colFormLabel" placeholder="1132283419" name="telefone"
                        readonly>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="colsm-2 form-label">Celular</label>
                <div class="col-sm-10">
                    <input type="tel" class="form-control" id="colFormLabel" placeholder="11991236464" name="sexo"
                        readonly>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">E-mail</label>
                <div class="col-sm-10">
                    <input type="email" class="form-control" id="colFormLabel" placeholder="usuario@gmail.com.br"
                        name="email" readonly>
                </div>
            </div>

            <!--residencia-->

            <div class="title">
                <h2 class="title-2">Residência</h2>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="colsm-2 form-label">CEP</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="colFormLabel" placeholder="18086765" name="cep"
                        readonly>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="colsm-2 form-label">Estado</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="colFormLabel" placeholder="São Paulo" name="estado"
                        readonly>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Cidade</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="colFormLabel" placeholder="Sorocaba" name="cidade"
                        readonly>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Bairro</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="colFormLabel" placeholder="Jardim Maria Eugênia"
                        name="bairro" readonly>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Rua</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="colFormLabel" placeholder="Roberto de Souza" name="rua"
                        readonly>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Número</label>
                <div class="col-sm-10 mb-3">
                    <input type="number" class="form-control" id="colFormLabel" placeholder="159" name="cidade"
                        readonly>
                </div>
            </div>

            <!--Experiências-->
            <div class="title">
                <h2 class="title-2">Experiências</h2>
            </div>

            <div id="Exp">
                <div class="subtitle">
                    <h3 class="title-3">Experiência</h3>
                    <h3 class="numExp">1</h3>
                </div>

                <div class="row mb-3">
                    <input type="text" class="col form-control dual" id="colFormLabel" placeholder="" name="formacao"
                        readonly>

                    <input type="text" class="col form-control dual" id="colFormLabel" placeholder="" name="status"
                        readonly>
                </div>

                <div class="row">
                    <label for="colFormLabel" class="col-sm-2 form-label exp-label">Anos de Experiência:</label>
                    <div class="col number mb-3">
                        <input type="number" class="form-control cl-exp-anos-experiencia" id="colFormLabel"
                            placeholder="" name="exp-anos-experiencia-1" readonly>
                    </div>
                </div>
            </div>

            <!--Competências-->
            <div class="title">
                <h2 class="title-2">Competências</h2>
            </div>

            <div id="Comp">
                <div class="subtitle">
                    <h3 class="title-3">Competência</h3>
                    <h3 class="numComp">1</h3>
                </div>

                <div class="row mb-3">
                    <input type="text" class="col form-control dual" id="colFormLabel" placeholder="" name="nome"
                        readonly>

                    <input type="text" class="col form-control dual" id="colFormLabel" placeholder="" name="grau"
                        readonly>
                </div>

                <div class="row">
                    <div class="col mb-3 form-align">
                        <input type="text" class="form-control" id="colFormLabel" placeholder="" name="status" readonly>
                    </div>
                </div>
            </div>

            <!--Formações-->
            <div class="title">
                <h2 class="title-2">Formações</h2>
            </div>

            <div id="Form">
                <div class="subtitle">
                    <h3 class="title-3">Formação</h3>
                    <h3 class="numForm">1</h3>
                </div>

                <div class="row mb-3">
                    <input type="text" class="col form-control dual" id="colFormLabel" placeholder="" name="tipo"
                        readonly>

                    <input type="text" class="col form-control dual" id="colFormLabel" placeholder="" name="status"
                        readonly>
                </div>

                <div class="row">
                    <input type="text" class="col form-control dual" id="colFormLabel" placeholder="" name="nome"
                        readonly>

                    <input type="text" class="col form-control dual mb-3" id="colFormLabel" placeholder="" name="grau"
                        readonly>
                </div>
            </div>

            <!--Currículo-->
            <div class="title">
                <h2 class="title-2">Currículo</h2>
            </div>

            <div class="row">
                <div class="col col-pdf">
                    <img class="pdf" src="/images/custom-perfil/pdf.svg">
                </div>

                <div class="col col-btns">
                    <div class="buttons">
                        <button type="button" class="btn btn-outline-primary mb-2">
                            <img src="/images/custom-perfil/download.svg">
                            Download</button>
                    </div>
                    <div class="buttons">
                        <button type="button" class="btn btn-outline-primary mb-5">
                            <img src="/images/custom-perfil/view.svg">
                            Visualizar</button>
                    </div>
                </div>
            </div>


            <div class="buttons-bottom">
                <button type="button" class="btn btn-outline-primary mb-5">Voltar</button>
                <button type="button" class="btn btn-outline-primary btn-excluir mb-5"
                    onclick="Open('popup-confirm')">Excluir Candidato</button>
            </div>
        </div>
    </form>

    <!--Footer-->
    <footer class="footer">
        <img src="/images/global/linkedin.svg" class="img-footer" onclick="">
        <img src="/images/global/facebook.svg" class="img-footer" onclick="">
        <img src="/images/global/email.svg" class="img-footer" onclick="">
        <label class="label-footer">+55 (15) 5555-5555</label>
    </footer>

    <!--Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ"
        crossorigin="anonymous"></script>

    <script src="/scripts/manager-scripts/gerar-requisicao-de-vaga.js"></script>
    <script src="/scripts/general-scripts/pop-up.js"></script>
</body>

</html>