<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Visualizar Processo Seletivo</title>

    <!-- Bootstrap / CSS -->
    <link rel="stylesheet" href="/styles/custom-visualizar-processo-seletivo.css">
    <link rel="stylesheet" href="/styles/pop-up.css">

</head>

<body>
    <!--Header-->
    <nav class="navbar navbar-expand-lg navbar-dark" id="header">
        <div class="container-fluid background-navbar">
            <a class="navbar-brand" href="/home"><img src="/images/global/logo.svg" alt=""></a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">
                <img src="/images/global/navbar-button.svg" class="navbar-button">
            </button>
            <?php if($_SESSION['tipo_user'] == 2) { ?>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" href="/home">Home</a>
                    <a class="nav-link" href="">Funcionário</a>
                    <a class="nav-link" href="/gerenciar_candidato">Candidatos</a>
                    <a class="nav-link" href="/gerenciar_vaga">Vagas</a>
                    <a class="nav-link active" href="/gerenciar_processo_seletivo">Processos Seletivos</a>
                    <a class="nav-link" href="/gerenciar_entrevista_candidato">Entrevistas</a>
                    <a class="nav-link" href="/gerar_relatorio">Relatórios</a>
                    <a class="nav-link" href="/usuario_sair">Sair</a>
                </div>
            </div>
            <?php } elseif($_SESSION['tipo_user'] == 3){ ?>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" href="/home">Home</a>
                    <a class="nav-link" href="">Gestor</a>
                    <a class="nav-link" href="/requisicoes_vaga">Requisições</a>
                    <a class="nav-link active" href="/gerenciar_processo_seletivo">Processos Seletivos</a>
                    <a class="nav-link" href="/gerenciar_entrevista_candidato">Entrevistas</a>
                    <a class="nav-link" href="/usuario_sair">Sair</a>
                </div>
            </div>
            <?php } elseif($_SESSION['tipo_user'] == 4){ ?>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" href="/home">Home</a>
                    <a class="nav-link" href="">Líder</a>
                    <a class="nav-link" href="/requisicoes_vaga">Requisições</a>
                    <a class="nav-link active" href="/gerenciar_processo_seletivo">Processos Seletivos</a>
                    <a class="nav-link" href="/gerenciar_entrevista_candidato">Entrevistas</a>
                    <a class="nav-link" href="/usuario_sair">Sair</a>
                </div>
            </div>
            <?php } else { ?>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" href="/home">Home</a>
                    <a class="nav-link" href="">Admin</a>
                    <a class="nav-link" href="/gerenciar_candidato">Candidatos</a>
                    <a class="nav-link" href="/requisicoes_vaga">Requisições</a>
                    <a class="nav-link" href="/gerenciar_vaga">Vagas</a>
                    <a class="nav-link active" href="/gerenciar_processo_seletivo">Processos Seletivos</a>
                    <a class="nav-link" href="/gerenciar_entrevista_candidato">Entrevistas</a>
                    <a class="nav-link" href="/gerar_relatorio">Relatórios</a>
                    <a class="nav-link" href="/usuario_sair">Sair</a>
                </div>
            </div>
            <?php } ?>

        </div>
    </nav>

    <!--Pop-up area-->
    <div class="popup-container" id="popup-confirm">
        <!--onclick="Open('popup-confirm')"-->
        <!--<link rel="stylesheet" href="../../../../Public/styles/pop-up.css">-->
        <!--<script src="../../../../Public/scripts/general-scripts/pop-up.js"></script>-->
        <div class="popup-content">
            <div class="popup-close" title="Close">
                <img src="/images/global/close.svg" onclick="Close(this)">
            </div>

            <img src="/images/pop-up/alert.svg" class="popup-img">

            <h1 class="popup-title">Alterar Processo</h1>

            <p class="popup-description">Tem certeza que deseja alterar o processo seletivo? Você poderá atualizar as
                informações a qualquer momento.</p>

            <button class="popup-btn popup-btn-width" onclick="Confirm(this)">
                Confirmar
            </button>

            <button type="button" class="popup-btn-link" onclick="Close(this)">
                Voltar
            </button>
        </div>
    </div>

    <div class="popup-container" id="popup-confirm2">
        <!--onclick="Open('popup-confirm2')"-->
        <!--<link rel="stylesheet" href="../../../../Public/styles/pop-up.css">-->
        <!--<script src="../../../../Public/scripts/general-scripts/pop-up.js"></script>-->
        <div class="popup-content">
            <div class="popup-close" title="Close">
                <img src="/images/global/close.svg" onclick="Close(this)">
            </div>

            <img src="/images/pop-up/alert.svg" class="popup-img">

            <h1 class="popup-title">Excluir Processo</h1>

            <p class="popup-description">Tem certeza que deseja excluir o processo seletivo? Todos os dados do processo
                seletivo serão perdidos.</p>

            <button class="popup-btn popup-btn-width" onclick="Confirm(this)">
                Confirmar
            </button>

            <button type="button" class="popup-btn-link" onclick="Close(this)">
                Voltar
            </button>
        </div>
    </div>

    <div class="popup-container" id="popup-back">
        <!--onclick="Open('popup-back')"-->
        <!--<link rel="stylesheet" href="../../../../Public/styles/pop-up.css">-->
        <!--<script src="../../../../Public/scripts/general-scripts/pop-up.js"></script>-->
        <div class="popup-content">
            <div class="popup-close" title="Close">
                <img src="/images/global/close.svg" onclick="Close(this)">
            </div>

            <img src="/images/pop-up/alert.svg" class="popup-img">

            <h1 class="popup-title">Voltar</h1>

            <p class="popup-description">Tem certeza que deseja voltar para a página anterior? Todas as alterações serão
                perdidas</p>

            <button class="popup-btn popup-btn-width" onclick="Back(this, '/gerenciar_processo_seletivo')">
                Confirmar
            </button>

            <button type="button" class="popup-btn-link" onclick="Close(this)">
                Voltar
            </button>
        </div>
    </div>

    <!--Page user-->

        <?php if($_SESSION['tipo_user'] == 2 || $_SESSION['tipo_user'] == 5){ ?>
        <div class="container">
            <div class="title">
                <h1 class="title-1">Visualizar Processo Seletivo</h1>
            </div>

            <div class="title">
                <h2 class="title-2">Dados de Cadastro</h2>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="colsm-2 form-label title-interview">Título</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="colFormLabel"
                        value="<?= $this->view->detalhesProcessoSeletivo->titulo_proc ?>" placeholder=""
                        name="tituloProcSeletivo">
                </div>
            </div>
            <div class="row mb-3">
                <label for="vacancy" class="col-sm-2 form-label form-label">Vaga</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="colFormLabel" value="" name="vacancy">
                </div>
            </div>
            <div class="row mb-3">
                <label for="responsible" class="col-sm-2 form-label form-label">Responsável</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="colFormLabel"
                        value="<?= $this->view->detalhesProcessoSeletivo->nome ?>" name="responsible">
                </div>
            </div>

            <div class="title">
                <h2 class="title-2">Dados do Processo</h2>
            </div>

            <div class="row mb-3">
                <div class="row mb-3">
                    <label for="start_date" class="col-sm-2 form-label form-label">Data de Início</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control"
                            value="<?= $this->view->detalhesProcessoSeletivo->data_inicio ?>" name="start_date">
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="end_date" class="col-sm-2 form-label form-label">Data de Término</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control"
                            value="<?= $this->view->detalhesProcessoSeletivo->data_termino ?>" name="end_date">
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="teste_Title" class="col-sm-2 form-label form-label">Classificação</label>
                    <div class="col-sm-10">
                        <input type="number" class="form-control" id="colFormLabel"
                            value="<?= $this->view->detalhesProcessoSeletivo->regra_class ?>" name="classification-rule"
                            min="0" step="0.1" max="1">
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="teste_Title" class="col-sm-2 form-label form-label">Descrição</label>
                    <textarea style="height: 70px;" type="text" class="form-control text-area"
                        name="descProc"><?=$this->view->detalhesProcessoSeletivo->descricao ?></textarea>
                </div>

                <?php 
                    $status = $this->view->detalhesProcessoSeletivo->status_proc;
                ?>

                <div class="row vagas">
                    <!--6%-->
                    <div class="title">
                        <h2 class="title-2">Status</h2>
                        <br>
                        <br>
                    </div>

                    <div class="mb-3 vaga" id="1-etapa">
                        <div class="vaga-bar">
                            <div class="vaga-per-6" per="6%"></div>
                        </div>

                        <div class="mb-3 texts">
                            <div class="text-box">
                                <span>Aberto</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Divulgado</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Testes</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Entrevistas</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Finalizado</span>
                                <img src="">
                            </div>
                        </div>

                    </div>

                    <!--28%-->
                    <div class="mb-3 vaga" id="2-etapa">
                        <div class="vaga-bar">
                            <div class="vaga-per-24" per="28%"></div>
                        </div>

                        <div class="mb-3 texts">
                            <div class="text-box">
                                <span>Aberto</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Divulgado</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Testes</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Entrevistas</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Finalizado</span>
                                <img src="">
                            </div>
                        </div>

                    </div>

                    <!--50%-->
                    <div class="mb-3 vaga" id="3-etapa">
                        <div class="vaga-bar">
                            <div class="vaga-per-59" per="50%"></div>
                        </div>

                        <div class="mb-3 texts">
                            <div class="text-box">
                                <span>Aberto</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Divulgado</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Testes</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Entrevistas</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Finalizado</span>
                                <img src="">
                            </div>
                        </div>

                    </div>

                    <!--72%-->
                    <div class="vaga" id="4-etapa">
                        <div class="vaga-bar">
                            <div class="vaga-per-77" per="72%"></div>
                        </div>

                        <div class="mb-3 texts">
                            <div class="text-box">
                                <span>Aberto</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Divulgado</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Testes</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Entrevistas</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Finalizado</span>
                                <img src="">
                            </div>
                        </div>

                    </div>

                    <!--100%-->
                    <div class="vaga" id="5-etapa">
                        <div class="vaga-bar">
                            <div class="vaga-per-100" per="100%"></div>
                        </div>

                        <div class="mb-3 texts">
                            <div class="text-box">
                                <span>Aberto</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Divulgado</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Testes</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Entrevistas</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Finalizado</span>
                                <img src="">
                            </div>
                        </div>

                    </div>
                </div>
            </div>
                <?php if($this->view->idTeste->status_teste == 'Criado' || $this->view->idTeste->status_teste == 'Liberado'){ ?>
                        <a href=""><button id="divulgar" type="submit" class="btn btn-outline-primary mb-4" disabled>Atribuir Teste</button></a>
                <?php } else {?>
                        <a href="/atribuir_teste?id_proc=<?= $this->view->detalhesProcessoSeletivo->id_proc ?>"><button type="submit" class="btn btn-outline-primary mb-4">Atribuir Teste</button></a> 
            <?php } ?>
            

                <?php if($this->view->idTeste->status_teste == 'Liberado' && $this->view->detalhesProcessoSeletivo->id_proc != 'Divulgado'){ ?>
                        <button id="testeDis" type="submit" class="btn btn-outline-primary mb-5" disabled>Liberar Teste</button>
                        <input type="hidden" name="id_teste">
                        <?php } else {?>
                            <a href="/liberar_teste?id_teste=<?= $this->view->idTeste->id_teste ?>&id_proc=<?= $this->view->detalhesProcessoSeletivo->id_proc ?>"><button id="teste" type="submit" class="btn btn-outline-primary mb-4">Liberar Teste</button></a> 
                    <?php } ?>
            <hr />

            <div class="buttons">
                <button type="button" class="btn btn-outline-primary mb-5" onclick="Open('popup-back')">Voltar</button>
                <button type="button" class="btn excluir btn-outline-primary mb-5"
                    onclick="Open('popup-confirm2')">Excluir</button>
                <button type="button" class="btn aprovar btn-outline-primary mb-5"
                    onclick="Open('popup-confirm')">Salvar</button>
            </div>
        </div>
        <?php } else { ?>
        <div class="container">
            <div class="title">
                <h1 class="title-1">Processo Seletivo</h1>
            </div>

            <div class="title">
                <h2 class="title-2">Dados de Cadastro</h2>
                <img src="/images/global/info.svg">
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="colsm-2 form-label title-interview">Título</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="colFormLabel"
                        value="<?= $this->view->detalhesProcessoSeletivo->titulo_proc ?>" placeholder=""
                        name="tituloProcSeletivo" disabled>
                </div>
            </div>
            <div class="row mb-3">
                <label for="vacancy" class="col-sm-2 form-label form-label">Vaga</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="colFormLabel" value="" name="vacancy" disabled>
                </div>
            </div>
            <div class="row mb-3">
                <label for="responsible" class="col-sm-2 form-label form-label">Responsável</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="colFormLabel"
                        value="<?= $this->view->detalhesProcessoSeletivo->nome ?>" name="responsible" disabled>
                </div>
            </div>

            <div class="title">
                <h2 class="title-2">Dados do Processo</h2>
                <img src="/images/global/info.svg">
            </div>

            <div class="row mb-3">
                <div class="row mb-3">
                    <label for="start_date" class="col-sm-2 form-label form-label">Data de Início</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control"
                            value="<?= $this->view->detalhesProcessoSeletivo->data_inicio ?>" name="start_date"
                            disabled>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="end_date" class="col-sm-2 form-label form-label">Data de Término</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control"
                            value="<?= $this->view->detalhesProcessoSeletivo->data_termino ?>" name="end_date" disabled>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="teste_Title" class="col-sm-2 form-label form-label">Classificação</label>
                    <div class="col-sm-10">
                        <input type="number" class="form-control" id="colFormLabel"
                            value="<?= $this->view->detalhesProcessoSeletivo->regra_class ?>" name="classification-rule"
                            min="0" step="0.1" max="1" disabled>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="teste_Title" class="col-sm-2 form-label form-label">Descrição</label>
                    <textarea style="height: 70px;" type="text" class="form-control text-area" name="descProc"
                        disabled><?=$this->view->detalhesProcessoSeletivo->descricao ?></textarea>
                </div>

                <?php 
                    $status = $this->view->detalhesProcessoSeletivo->status_proc;
                ?>

                <div class="row vagas">
                    <!--6%-->
                    <div class="title">
                        <h2 class="title-2">Status</h2>
                        <br>
                        <br>
                    </div>

                    <div class="mb-3 vaga" id="1-etapa">
                        <div class="vaga-bar">
                            <div class="vaga-per-6" per="6%"></div>
                        </div>

                        <div class="mb-3 texts">
                            <div class="text-box">
                                <span>Aberto</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Divulgado</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Testes</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Entrevistas</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Finalizado</span>
                                <img src="">
                            </div>
                        </div>

                    </div>

                    <!--28%-->
                    <div class="mb-3 vaga" id="2-etapa">
                        <div class="vaga-bar">
                            <div class="vaga-per-24" per="28%"></div>
                        </div>

                        <div class="mb-3 texts">
                            <div class="text-box">
                                <span>Aberto</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Divulgado</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Testes</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Entrevistas</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Finalizado</span>
                                <img src="">
                            </div>
                        </div>

                    </div>

                    <!--50%-->
                    <div class="mb-3 vaga" id="3-etapa">
                        <div class="vaga-bar">
                            <div class="vaga-per-59" per="50%"></div>
                        </div>

                        <div class="mb-3 texts">
                            <div class="text-box">
                                <span>Aberto</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Divulgado</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Testes</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Entrevistas</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Finalizado</span>
                                <img src="">
                            </div>
                        </div>

                    </div>

                    <!--72%-->
                    <div class="vaga" id="4-etapa">
                        <div class="vaga-bar">
                            <div class="vaga-per-77" per="72%"></div>
                        </div>

                        <div class="mb-3 texts">
                            <div class="text-box">
                                <span>Aberto</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Divulgado</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Testes</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Entrevistas</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Finalizado</span>
                                <img src="">
                            </div>
                        </div>

                    </div>

                    <!--100%-->
                    <div class="vaga" id="5-etapa">
                        <div class="vaga-bar">
                            <div class="vaga-per-100" per="100%"></div>
                        </div>

                        <div class="mb-3 texts">
                            <div class="text-box">
                                <span>Aberto</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Divulgado</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Testes</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Entrevistas</span>
                                <img src="">
                            </div>

                            <div class="text-box">
                                <span>Finalizado</span>
                                <img src="">
                            </div>
                        </div>

                    </div>
                </div>
            </div>

            <hr />

            <div class="buttons">
                <a href="/gerenciar_processo_seletivo"><button type="button"
                        class="btn btn-outline-primary mb-5">Voltar</button></a>
            </div>
        </div>
        <?php } ?>



    <!--Footer-->
    <footer class="footer">
        <!-- <img src="../../../../Public/images/global/linkedin.svg" class="img-footer" onclick="">
        <img src="../../../../Public/images/global/facebook.svg" class="img-footer" onclick="">
        <img src="../../../../Public/images/global/email.svg" class="img-footer" onclick=""> -->
        <img src="/images/global/linkedin.svg" class="img-footer" onclick="">
        <img src="/images/global/facebook.svg" class="img-footer" onclick="">
        <img src="/images/global/email.svg" class="img-footer" onclick="">
        <label class="label-footer">+55 (15) 5555-5555</label>
    </footer>

    <!--Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous">
    </script>

    <script src="/scripts/general-scripts/pop-up.js"></script>
</body>

</html>

<script language="javascript">
var status = "<?php print $status; ?>";

document.getElementById('1-etapa').style.display = 'none';
document.getElementById('2-etapa').style.display = 'none';
document.getElementById('3-etapa').style.display = 'none';
document.getElementById('4-etapa').style.display = 'none';
document.getElementById('5-etapa').style.display = 'none';

if (status == "Aberto")
    document.getElementById('1-etapa').style.display = 'block';
else if (status == 'Divulgado')
    document.getElementById('2-etapa').style.display = 'block';
else if (status == 'Testes')
    document.getElementById('3-etapa').style.display = 'block';
else if (status == 'Entrevistas')
    document.getElementById('4-etapa').style.display = 'block';
else
    document.getElementById('5-etapa').style.display = 'block';


var btn = document.getElementById('btnLiberarTeste');

btn.disabled = true;

if (status == "Divulgado")
    btn.disabled = false;
else
    btn.disabled = true;
</script>