<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registrar Entrevista</title>

    <!-- Bootstrap / CSS -->
    <link rel="stylesheet" href="/styles/custom-registrar-entrevista.css">
    <link rel="stylesheet" href="/styles/pop-up.css">
</head>

<body>

    <!--Header-->
    <nav class="navbar navbar-expand-lg navbar-dark" id="header">
        <div class="container-fluid background-navbar">
            <a class="navbar-brand" href="#"><img src="/images/global/logo.svg" alt=""></a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">
                <img src="/images/global/navbar-button.svg" class="navbar-button">
            </button>

            <?php if($_SESSION['tipo_user'] == 2) { ?>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" href="/home">Home</a>
                        <a class="nav-link" href="">Funcionário</a>
                        <a class="nav-link" href="/gerenciar_candidato">Candidatos</a>
                        <a class="nav-link" href="/gerenciar_vaga">Vagas</a>
                        <a class="nav-link" href="/gerenciar_processo_seletivo">Processos Seletivos</a>
                        <a class="nav-link active" href="/gerenciar_entrevista_candidato">Entrevistas</a>
                        <a class="nav-link" href="/gerar_relatorio">Relatórios</a>
                        <a class="nav-link" href="/usuario_sair">Sair</a>
                    </div>
                </div>
            <?php } elseif($_SESSION['tipo_user'] == 3){ ?>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" href="/home">Home</a>
                        <a class="nav-link" href="">Gestor</a>
                        <a class="nav-link" href="/requisicoes_vaga">Requisições</a>
                        <a class="nav-link" href="/gerenciar_processo_seletivo">Processos Seletivos</a>
                        <a class="nav-link active" href="/gerenciar_entrevista_candidato">Entrevistas</a>
                        <a class="nav-link" href="/usuario_sair">Sair</a>               
                    </div>
                </div>
            <?php } elseif($_SESSION['tipo_user'] == 4){ ?>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" href="/home">Home</a>
                        <a class="nav-link" href="">Líder</a>
                        <a class="nav-link" href="/requisicoes_vaga">Requisições</a>
                        <a class="nav-link" href="/gerenciar_processo_seletivo">Processos Seletivos</a>
                        <a class="nav-link active" href="/gerenciar_entrevista_candidato">Entrevistas</a>
                        <a class="nav-link" href="/usuario_sair">Sair</a>               
                    </div>
                </div>
            <?php } else { ?>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" href="/home">Home</a>
                        <a class="nav-link" href="">Admin</a>
                        <a class="nav-link" href="/gerenciar_candidato">Candidatos</a>
                        <a class="nav-link" href="/requisicoes_vaga">Requisições</a>
                        <a class="nav-link" href="/gerenciar_vaga">Vagas</a>
                        <a class="nav-link" href="/gerenciar_processo_seletivo">Processos Seletivos</a>
                        <a class="nav-link active" href="/gerenciar_entrevista_candidato">Entrevistas</a>
                        <a class="nav-link" href="/gerar_relatorio">Relatórios</a>
                        <a class="nav-link" href="/usuario_sair">Sair</a>
                    </div>
                </div>
             <?php } ?>
        </div>
    </nav>

    <?php
        if (isset($_GET['entrevistaRegistrar'])) {
        ?>

    <script>
    alert("Registro da Entrevista Realizado com Sucesso!");
    </script>

    <?php
        }
        ?>

    <!-- Php area -->
    <div class="popup-container" id="popup-confirm">
        <!--onclick="Open('popup-confirm')"-->
        <!--<link rel="stylesheet" href="../../../../Public/styles/pop-up.css">-->
        <!--<script src="../../../../Public/scripts/general-scripts/pop-up.js"></script>-->
        <div class="popup-content">
            <div class="popup-close" title="Close">
                <img src="/images/global/close.svg" onclick="Close(this)">
            </div>

            <img src="/images/pop-up/alert.svg" class="popup-img">

            <h1 class="popup-title">Salvar Entrevista</h1>

            <p class="popup-description">Tem certeza que deseja salvar a entrevista?</p>

            <button class="popup-btn popup-btn-width" onclick="Confirm(this)">
                Confirmar
            </button>

            <button type="button" class="popup-btn-link" onclick="Close(this)">
                Voltar
            </button>
        </div>
    </div>

    <div class="popup-container" id="popup-back">
        <!--onclick="Open('popup-back')"-->
        <!--<link rel="stylesheet" href="../../../../Public/styles/pop-up.css">-->
        <!--<script src="../../../../Public/scripts/general-scripts/pop-up.js"></script>-->
        <div class="popup-content">
            <div class="popup-close" title="Close">
                <img src="/images/global/close.svg" onclick="Close(this)">
            </div>

            <img src="/images/pop-up/alert.svg" class="popup-img">

            <h1 class="popup-title">Voltar</h1>

            <p class="popup-description">Tem certeza que deseja cancelar o registro? Após voltar para a tela
                anterior, todas as informações inseridas serão perdidas.</p>

            <button class="popup-btn popup-btn-width" onclick="Back(this, 'url')">
                Confirmar
            </button>

            <button type="button" class="popup-btn-link" onclick="Close(this)">
                Voltar
            </button>
        </div>
    </div>

    <!-- Page user -->
    <form action="entrevista_candidato_registrar" method="post" id="formulario">
        <div class="container">
            <div class="title">
                <h1 class="title-1">Registrar Entrevista</h1>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="colsm-2 form-label label">Responsável</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control form" id="colFormLabel" readonly placeholder="" name="resp">
                </div>
            </div>
            <div class="row mb-3">
                <label for="role" class="col-sm-2 form-label label">Processo Seletivo</label>
                <div class="col-sm-10">
                    <select class="col form-select" name="role">
                        <option selected></option>
                        <option value="1">#</option>
                        <option value="2">#</option>
                        <option value="3">#</option>
                    </select>
                </div>
            </div>
            <div class="row mb-3">
                <label for="applpicant" class="col-sm-2 form-label label">Candidato</label>
                <div class="col-sm-10">
                    <select class="col form-select" name="applpicant">
                        <option selected></option>
                        <option value="1">#</option>
                        <option value="2">#</option>
                        <option value="3">#</option>
                    </select>
                </div>
            </div>

            <hr />

            <div>
                <div class="title">
                    <h2 class="title-2">Estilo Comportamental <img class="icon" src="/images/global/edit.svg"
                            alt="edit"></h2>
                </div>
                <div class="col-sm-12 mb-3">
                    <textarea type="text" class="form-control text-area" name="behavioral_style"></textarea>
                </div>
            </div>

            <div>
                <div class="title">
                    <h2 class="title-2">Pontos Positivos <img class="icon" src="/images/global/edit.svg" alt="edit">
                    </h2>
                </div>
                <div class="col-sm-12 mb-3">
                    <textarea type="text" class="form-control text-area" name="positive_points"></textarea>
                </div>
            </div>

            <div>
                <div class="title">
                    <h2 class="title-2">Pontos Negativos <img class="icon" src="/images/global/edit.svg" alt="edit">
                    </h2>
                </div>
                <div class="col-sm-12 mb-3">
                    <textarea type="text" class="form-control text-area" name="negative_points"></textarea>
                </div>
            </div>

            <div class="buttons">
                <button type="button" class="btn btn-outline-primary mb-5" onclick="Open('popup-back')">Voltar</button>
                <button type="button" class="btn btn-outline-primary mb-5"
                    onclick="Open('popup-confirm')">Salvar</button>
                <!-- <button type="submit" class="btn btn-outline-primary mb-5">Registrar</button> -->
            </div>
        </div>
    </form>

    <!--Footer-->
    <footer class="footer">
        <a href="">
            <img src="/images/global/linkedin.svg" class="img-footer">
        </a>
        <a href="">
            <img src="/images/global/facebook.svg" class="img-footer">
        </a>
        <a href="">
            <img src="/images/global/email.svg" class="img-footer">
        </a>
        <label class="label-footer">+55 (15) 5555-5555</label>
    </footer>

    <!--Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous">
    </script>

    <script src="/scripts/general-scripts/pop-up.js"></script>

</body>

</html>