<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gerenciar Entrevistas</title>

    <!-- Bootstrap / CSS -->
    <link rel="stylesheet" href="/styles/custom-gerenciar-entrevista.css">

</head>

<body>
    <!--Header-->
    <nav class="navbar navbar-expand-lg navbar-dark" id="header">
        <div class="container-fluid background-navbar">
            <a class="navbar-brand" href="/home"><img src="/images/global/logo.svg" alt=""></a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">
                <img src="/images/global/navbar-button.svg" class="navbar-button">
            </button>

            <?php if($_SESSION['tipo_user'] == 2) { ?>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" href="/home">Home</a>
                        <a class="nav-link" href="">Funcionário</a>
                        <a class="nav-link" href="/gerenciar_candidato">Candidatos</a>
                        <a class="nav-link" href="/gerenciar_vaga">Vagas</a>
                        <a class="nav-link" href="/gerenciar_processo_seletivo">Processos Seletivos</a>
                        <a class="nav-link active" href="/gerenciar_entrevista_candidato">Entrevistas</a>
                        <a class="nav-link" href="/gerar_relatorio">Relatórios</a>
                        <a class="nav-link" href="/usuario_sair">Sair</a>
                    </div>
                </div>
            <?php } elseif($_SESSION['tipo_user'] == 3){ ?>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" href="/home">Home</a>
                        <a class="nav-link" href="">Gestor</a>
                        <a class="nav-link" href="/requisicoes_vaga">Requisições</a>
                        <a class="nav-link" href="/gerenciar_processo_seletivo">Processos Seletivos</a>
                        <a class="nav-link active" href="/gerenciar_entrevista_candidato">Entrevistas</a>
                        <a class="nav-link" href="/usuario_sair">Sair</a>               
                    </div>
                </div>
            <?php } elseif($_SESSION['tipo_user'] == 4){ ?>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" href="/home">Home</a>
                        <a class="nav-link" href="">Líder</a>
                        <a class="nav-link" href="/requisicoes_vaga">Requisições</a>
                        <a class="nav-link" href="/gerenciar_processo_seletivo">Processos Seletivos</a>
                        <a class="nav-link active" href="/gerenciar_entrevista_candidato">Entrevistas</a>
                        <a class="nav-link" href="/usuario_sair">Sair</a>               
                    </div>
                </div>
            <?php } else { ?>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" href="/home">Home</a>
                        <a class="nav-link" href="">Admin</a>
                        <a class="nav-link" href="/gerenciar_candidato">Candidatos</a>
                        <a class="nav-link" href="/requisicoes_vaga">Requisições</a>
                        <a class="nav-link" href="/gerenciar_vaga">Vagas</a>
                        <a class="nav-link" href="/gerenciar_processo_seletivo">Processos Seletivos</a>
                        <a class="nav-link active" href="/gerenciar_entrevista_candidato">Entrevistas</a>
                        <a class="nav-link" href="/gerar_relatorio">Relatórios</a>
                        <a class="nav-link" href="/usuario_sair">Sair</a>
                    </div>
                </div>
             <?php } ?>
        </div>
    </nav>

    <div class="container">
        <div class="title">
            <h1 class="title-1">Gerenciar Entrevistas</h1>
        </div>

        <!--Pesquisa-->
        <div class="row mb-3">
            <label for="colFormLabel" class="col-sm-2 form-label">Processo Seletivo</label>
            <div class="col-sm-10">
                <select class="col form-select" aria-label="processo-seletivo" name="processo-seletivo">
                    <option selected>Todos</option>
                    <option value="1">#</option>
                    <option value="2">#</option>
                    <option value="3">#</option>
                </select>
            </div>
        </div>

        <div class="row mb-3">
            <label for="colFormLabel" class="col-sm-2 form-label">Organizar por</label>

            <select class="col-sm-10 form-select" aria-label="organizar-por" name="organizar-por">
                <option selected>Todas</option>
                <option value="1">#</option>
            </select>
        </div>

        <div class="btn-search">
            <a href="/gerenciar_entrevista_candidato"><button type="button"
                    class="btn btn-outline-primary mb-5">Marcadas</button></a>
            <a href="/entrevista_registrada"><button type="button"
                    class="btn btn-outline-primary mb-5 roxo">Registradas</button></a>
        </div>

        <hr>

        <!--Resposta-->
        <?php foreach($this->view->todasEntrevistasRegistradas as $key => $entrevistaRegistrada) {?>
        <form action="/visualizar_entrevista_registrada" method="post">
            <div class="candidato">
                <div class="card">
                    <div class="card-img"></div>

                    <div class="card-body">
                        <!-- <h4 class="card-title">Departamento: <?= $entrevistaRegistrada->est_comp ?> </h4> -->
                        <h4 class="card-title" id="nome-candidato">
                            <!-- <?= $entrevistaRegistrada->est_comp ?> -->
                        </h4>
                        <p class="card-text title-user" id="hora-entrevista">
                            <?= $entrevistaRegistrada->est_comp ?> -
                            <?= $entrevistaRegistrada->est_comp ?>
                        </p>
                    </div>
                </div>
                <!-- <button type="button" class="btn btn-outline-primary mb-4">Divulgar</button> -->
                <button type="submit" class="btn btn-outline-primary mb-4">Visualizar</button>
                <input type="hidden" name="id_entrevista" value="<?= $entrevistaRegistrada->id_entrevista ?>">
            </div>
        </form>
        <?php } ?>

        <div class="buttons">
            <button type="button" class="btn btn-outline-primary mb-5"
                onclick="window.location.href = '/gerenciar_entrevista_candidato'">Voltar</button>
        </div>

    </div>

    <!--Footer-->
    <footer class="footer">
        <img src="/images/global/linkedin.svg" class="img-footer" onclick="">
        <img src="/images/global/facebook.svg" class="img-footer" onclick="">
        <img src="/images/global/email.svg" class="img-footer" onclick="">
        <label class="label-footer">+55 (15) 5555-5555</label>
    </footer>


    <!--Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ"
        crossorigin="anonymous"></script>

    <script src=""></script>
</body>

</html>