<!doctype html>
<html lang="pt-br">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap / CSS -->
    <link rel="stylesheet" href="/styles/custom-requisicao-de-vaga.css">
    <link rel="stylesheet" href="/styles/pop-up.css">

    <title>Gerar Requisição de Vaga</title>

    <script type="text/javascript">
        let cargos = <?php echo json_encode($this->view->cargos) ?>;
    </script>
</head>

<body>
    <!--Header-->
    <nav class="navbar navbar-expand-lg navbar-dark" id="header">
        <div class="container-fluid background-navbar">
            <a class="navbar-brand" href="/"><img src="/images/global/logo.svg" alt=""></a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">
                <img src="/images/global/navbar-button.svg" class="navbar-button">
            </button>

            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" href="/home">Home</a>
                        <a class="nav-link" href="">Gestor</a>
                        <a class="nav-link active" href="/requisicoes_vaga">Requisições</a>
                        <a class="nav-link" href="/gerenciar_processo_seletivo">Processos Seletivos</a>
                        <a class="nav-link" href="/gerenciar_entrevista_candidato">Entrevistas</a>
                        <a class="nav-link" href="/usuario_sair">Sair</a>               
                    </div>
                </div>
        </div>
    </nav>

    <!-- Pop-up area -->
    <div class="popup-container" id="popup-confirm">
        <!--onclick="Open('popup-confirm')"-->
        <!--<link rel="stylesheet" href="../../../../Public/styles/pop-up.css">-->
        <!--<script src="../../../../Public/scripts/general-scripts/pop-up.js"></script>-->
        <div class="popup-content">
            <div class="popup-close" title="Close">
                <img src="/images/global/close.svg" onclick="Close(this)">
            </div>

            <img src="/images/pop-up/alert.svg" class="popup-img">

            <h1 class="popup-title">Gerar Requisição</h1>

            <p class="popup-description">Tem certeza que deseja gerar esta requsicição de vaga?</p>

            <button class="popup-btn popup-btn-width" onclick="Confirm(this, '/requisicoes_vaga')">
                Confirmar
            </button>

            <button type="button" class="popup-btn-link" onclick="Close(this)">
                Voltar
            </button>
        </div>
    </div>

    <div class="popup-container" id="popup-back">
        <!--onclick="Open('popup-back')"-->
        <!--<link rel="stylesheet" href="../../../../Public/styles/pop-up.css">-->
        <!--<script src="../../../../Public/scripts/general-scripts/pop-up.js"></script>-->
        <div class="popup-content">
            <div class="popup-close" title="Close">
                <img src="/images/global/close.svg" onclick="Close(this)">
            </div>

            <img src="/images/pop-up/alert.svg" class="popup-img">

            <h1 class="popup-title">Voltar</h1>

            <p class="popup-description">Tem certeza que deseja cancelar a requisição? Todas as informações inseridas
                serão perdidas.</p>

            <button class="popup-btn popup-btn-width" onclick="Back(this, '/requisicoes_vaga')">
                Confirmar
            </button>

            <button type="button" class="popup-btn-link" onclick="Close(this)">
                Voltar
            </button>
        </div>
    </div>

    <!--Page user-->
    <form action="/gerar_vaga" method="post" id="formulario">
        <div class="container">

            <div class="title">
                <h1 class="title-1">Gerar Requisição de Vaga</h1>
            </div>

            <!--Dados de Solicitaçao-->
            <div class="title">
                <h2 class="title-2">Dados de Solicitação</h2>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="colsm-2 form-label title-interview">Título da Vaga</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control form1" id="colFormLabel" placeholder="" name="titulo_vaga"
                        required>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="colsm-2 form-label">Requisitante</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control form1" id="colFormLabel" placeholder="" name="requisitante"
                        value="<?=$_SESSION['nome']?>" readonly>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Data de Solicitação</label>
                <div class="col-sm-10">
                    <input type="date" class="form-control form1" id="colFormLabel" placeholder=""
                        name="data_solicitacao" pattern="[0-9]{2}\/[0-9]{2}\/[0-9]{4}$" required>
                </div>
            </div>

            <!--Dados de Vaga-->
            <div class="title">
                <h2 class="title-2">Dados de Vaga</h2>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Departamento</label>
                <div class="col-sm-10">
                    <select class="col form-select form1" name="departamento" onchange="atribuitDept(this)" required> 
                        <option selected value="0">--Selecione--</option>
                        <?php foreach ($this->view->departamentos as $key => $departamento) { ?>
                        <option value="<?=$departamento->id_departamento?>">
                            <?= $departamento->nome_departamento ?>
                        </option>
                        <?php } ?>
                    </select>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Cargo</label>
                <div class="col-sm-10">
                    <select class="col form-select form1" name="cargo" required>
                        <option selected value="0">--Selecione--</option>
                        <?php foreach ($this->view->cargos as $key => $cargo) { ?>
                        <option value="<?=$cargo->id_cargo?>">
                            <?= $cargo->nome_cargo ?>
                        </option>
                        <?php } ?>
                    </select>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Vínculo Empregatício</label>
                <div class="col-sm-10">
                    <select class="col form-select form1" aria-label="Formação" name="vinculo_empregaticio" required>
                        <option selected value="0">--Selecione--</option>
                        <option value="1">CLT</option>
                        <option value="2">PJ</option>
                        <option value="3">Estágio</option>
                    </select>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Salário</label>
                <div class="col-sm-10">
                    <input type="number" class="form-control form1" id="colFormLabel" placeholder="" name="salario"
                        step="0.01" min="0" required>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Horário de Trabalho</label>
                <div class="col-sm-10 input-1">
                    <input type="time" class="form-control form2" id="colFormLabel" placeholder=""
                        name="hora_trab_inicio" pattern="[0-9]{2}:[0-9]{2} [0-9]{2}$" required>
                </div>
                <label for="colFormLabel" class="col label-middle">à</label>
                <div class="col-sm-10 input-2">
                    <input type="time" class="form-control form2" id="colFormLabel" placeholder="" name="hora_trab_fim"
                        pattern="[0-9]{2}:[0-9]{2} [0-9]{2}$" required>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Número de Vagas</label>
                <div class="col-sm-10">
                    <input type="number" class="form-control form1" id="colFormLabel" placeholder="" name="numero_vagas"
                        min="0" required>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Função</label>
                <div class="col-sm-12 mb-3">
                    <textarea type="text" class="form-control" id="textarea" rows="3" name="funcao" required></textarea>
                </div>
            </div>

            <!--Experiências-->
            <div class="title">
                <h2 class="title-2">Experiências</h2>
            </div>

            <div id="Exp">
                <div class="subtitle">
                    <h3 class="title-3">Experiência</h3>
                    <h3 class="numExp">1</h3>
                </div>

                <div class="row mb-3">
                    <select class="col form-select cl-exp-formacao form3" aria-label="Experiência"
                        name="exp-formacao-1">
                        <option selected value="0">Experiência</option>
                        <option value="1">Administrativa</option>
                        <option value="2">Elétrica</option>
                        <option value="3">Eletrônica</option>
                        <option value="4">Recursos Humanos</option>
                        <option value="5">Redes</option>
                        <option value="6">Contábil</option>
                        <option value="7">Programação</option>
                        <option value="8">Logística</option>
                    </select>

                    <select class="col form-select cl-exp-status form3" aria-label="Status" name="exp-status-1">
                        <option selected value="0">Status</option>
                        <option value="1">Experiência Qualquer</option>
                        <option value="2">Júnior</option>
                        <option value="3">Pleno</option>
                        <option value="4">Sênior</option>
                    </select>
                </div>

                <div class="row">
                    <label for="colFormLabel" class="col-sm-2 form-label exp-label">Anos de Experiência:</label>
                    <div class="col number">
                        <input type="number" class="form-control cl-exp-anos-experiencia form2" id="colFormLabel"
                            placeholder="00" name="exp-anos-experiencia-1">
                    </div>
                </div>

                <div id="btn-area-0" class="btn-area-exp">
                    <img src="/images/custom-requisicao-de-vaga/plus.svg" class="btn-form" onclick="addExp()">
                    <img src="/images/custom-requisicao-de-vaga/minus.svg" class="btn-form" onclick="removeExp()">
                </div>
            </div>

            <!--Competências-->
            <div class="title">
                <h2 class="title-2">Competências</h2>
            </div>

            <div id="Comp">
                <div class="subtitle">
                    <h3 class="title-3">Competência</h3>
                    <h3 class="numComp">1</h3>
                </div>

                <div class="row mb-3">
                    <select class="col form-select cl-comp-nome form3" aria-label="Nome" name="comp-nome-1">
                        <option selected value="0">Nome</option>
                        <option value="1">Gestão de Pessoas</option>
                        <option value="2">Análise de Requisitos</option>
                        <option value="3">Java</option>
                        <option value="4">ERP</option>
                        <option value="5">Prestações de Contas</option>
                        <option value="6">Escrituração Fiscal</option>
                        <option value="7">Manutenção de Motores Trifásicos</option>
                        <option value="8">Gestão de Projetos</option>
                        <option value="9">Planejamento de Armazenagem de Mercadorias</option>
                        <option value="10">Inglês</option>
                    </select>

                    <select class="col form-select cl-comp-grau form3" aria-label="Grau" name="comp-grau-1">
                        <option selected value="0">Grau</option>
                        <option value="1">Básico</option>
                        <option value="2">Intermediário</option>
                        <option value="3">Avançado</option>
                    </select>
                </div>

                <div class="row">
                    <select class="col form-select cl-comp-status form4" aria-label="Status" name="comp-status-1">
                        <option selected value="0">Status</option>
                        <option value="1">Iniciante</option>
                        <option value="2">Em Desenvolvimento</option>
                        <option value="3">Concluído</option>
                    </select>
                </div>

                <div id="btn-area-comp-0" class="btn-area-comp">
                    <img src="/images/custom-requisicao-de-vaga/plus.svg" class="btn-form" onclick="addComp()">
                    <img src="/images/custom-requisicao-de-vaga/minus.svg" class="btn-form" onclick="removeComp()">
                </div>
            </div>

            <!--Formações-->
            <div class="title">
                <h2 class="title-2">Formações</h2>
            </div>

            <div id="Form">
                <div class="subtitle">
                    <h3 class="title-3">Formação</h3>
                    <h3 class="numForm">1</h3>
                </div>

                <div class="row mb-3">
                    <select class="col form-select cl-form-tipo form3" aria-label="Tipo" name="form-tipo-1">
                        <option selected value="0">Tipo</option>
                        <option value="1">Fundamental</option>
                        <option value="2">Ensino médio</option>
                        <option value="3">Técnico</option>
                        <option value="4">Superior</option>
                    </select>

                    <select class="col form-select cl-form-status form3" aria-label="Status" name="form-status-1">
                        <option selected value="0">Status</option>
                        <option value="1">Completo</option>
                        <option value="2">Em Andamento</option>
                        <option value="3">Incompleto</option>
                    </select>
                </div>

                <div class="row">
                    <select class="col form-select cl-form-nome form3" aria-label="Nome" name="form-nome-1">
                        <option selected value="0">Nome</option>
                        <option value="1">Análise e Desenvolvimento de Sistemas</option>
                        <option value="2">Redes</option>
                        <option value="3">Ciência da Computação</option>
                        <option value="4">Logística</option>
                        <option value="5">Contabilidade</option>
                        <option value="6">Engenharia Elétrica</option>
                        <option value="7">Engenharia Eletrônica</option>
                        <option value="8">Engenharia de Automação</option>
                        <option value="9">Recursos Humanos</option>
                        <option value="10">Administração</option>
                    </select>

                    <select class="col form-select cl-form-grau form3" aria-label="Grau" name="form-grau-1">
                        <option selected value="0">Grau</option>
                        <option value="1">Tecnólogo</option>
                        <option value="2">Graduação</option>
                        <option value="3">Pôs-graduação</option>
                        <option value="4">Mestrado</option>
                        <option value="4">Doutorado</option>
                    </select>
                </div>

                <div id="btn-area-form-0" class="btn-area-form">
                    <img src="/images/custom-requisicao-de-vaga/plus.svg" class="btn-form" onclick="addForm()">
                    <img src="/images/custom-requisicao-de-vaga/minus.svg" class="btn-form" onclick="removeForm()">
                </div>
            </div>

            <div class="buttons">
                <button type="button" class="btn btn-outline-primary mb-5" onclick="Open('popup-back')">Voltar</button>
                <button type="button" class="btn btn-outline-primary mb-5"
                    onclick="Open('popup-confirm')">Gerar</button>
            </div>
        </div>
    </form>

    <!--Footer-->
    <footer class="footer">
        <img src="/images/global/linkedin.svg" class="img-footer" onclick="">
        <img src="/images/global/facebook.svg" class="img-footer" onclick="">
        <img src="/images/global/email.svg" class="img-footer" onclick="">
        <label class="label-footer">+55 (15) 5555-5555</label>
    </footer>

    <!--Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous">
    </script>

    <script src="/scripts/manager-scripts/gerar-requisicao-de-vaga.js"></script>
    <script src="/scripts/general-scripts/pop-up.js"></script>
</body>

</html>