<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vagas Aprovadas</title>

    <!-- Bootstrap / CSS -->
    <link rel="stylesheet" href="styles/custom-requisicoes-de-vagas-aprovadas-e-reprovadas.css">
</head>
<body>
    <!--Header-->
    <nav class="navbar navbar-expand-lg navbar-dark" id="header">
        <div class="container-fluid background-navbar">
            <!-- <a class="navbar-brand" href="#"><img src="../../../../Public/images/global/logo.svg" alt=""></a> -->
            <a class="navbar-brand" href="/"><img src="images/global/logo.svg" alt=""></a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">
                <!-- <img src="../../../../Public/images/global/navbar-button.svg" class="navbar-button"> -->
                <img src="images/global/navbar-button.svg" class="navbar-button">
            </button>

            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <!--gestor-->
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" href="/home">Home</a>
                        <a class="nav-link" href="">Funcionário</a>
                        <a class="nav-link" href="/gerenciar_candidato">Candidatos</a>
                        <a class="nav-link active" href="/gerenciar_vaga">Vagas</a>
                        <a class="nav-link" href="/gerenciar_processo_seletivo">Processos Seletivos</a>
                        <a class="nav-link" href="/gerenciar_entrevista_candidato">Entrevistas</a>
                        <a class="nav-link" href="/gerar_relatorio">Relatórios</a>
                        <a class="nav-link" href="/usuario_sair">Sair</a>
                    </div>
                </div>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="title">
            <h1 class="title-1">Vagas Aprovadas</h1>
        </div>

        <!--Pesquisa-->
        <div class="row mb-3">
            <label for="colFormLabel" class="col-sm-2 form-label">Departamento</label>
            <div class="col-sm-10">
                <select class="col form-select" aria-label="Departamento" name="departamento">
                    <option selected>Todos</option>
                    <option value="1">#</option>
                    <option value="2">#</option>
                    <option value="3">#</option>
                </select>
            </div>
        </div>

        <div class="row mb-3">
            <label for="colFormLabel" class="col-sm-2 form-label">Cargo</label>
            <div class="col-sm-10">
                <select class="col form-select" aria-label="Cargo" name="cargo">
                    <option selected>Todos</option>
                    <option value="1">#</option>
                    <option value="2">#</option>
                    <option value="3">#</option>
                </select>
            </div>
        </div>

        <div class="row mb-3">
            <label for="colFormLabel" class="col-sm-2 form-label">Organizar por</label>

            <select class="col-sm-10 form-select" aria-label="organizar-por" name="organizar-por">
                <option selected>Todas</option>
                <option value="1">Aprovadas</option>
                <option value="2">Reprovadas</option>
            </select>
        </div>

        <hr>

        <!--Resposta-->
        <?php foreach($this->view->todasVagas as $key => $vaga) {?>
        <form action="/visualizar_vaga" method="post">
            <div class="depto-recursos-humanos">
                <div class="card">
                    <div class="card-img"></div>

                    <div class="card-body">
                        <h4 class="card-title">Departamento:
                            <?= $vaga->nome_departamento ?>
                        </h4>
                        <h6 class="card-text">
                            <?= $vaga->titulo_vaga ?>

                            <span>
                                - <?= $vaga->data_solic ?>
                            </span>

                            <span>
                                - <?= $vaga->status_vaga ?>
                            </span>
                        </h6>

                    </div>
                </div>
                <button type="submit" class="btn btn-outline-primary mb-4">Visualizar</button>
                <input type="hidden" name="id_vaga" value="<?= $vaga->id_vaga ?>">
            </div>
        </form>
        <?php } ?>

        <hr>

        <div class="buttons">
        <a href="/home"><button type="button" class="btn btn-outline-primary mb-5">Voltar</button></a>
        </div>

    </div>

    <!--Footer-->
    <footer class="footer">
        <!-- <img src="../../../../Public/images/global/linkedin.svg" class="img-footer" onclick="">
        <img src="../../../../Public/images/global/facebook.svg" class="img-footer" onclick="">
        <img src="../../../../Public/images/global/email.svg" class="img-footer" onclick=""> -->
        <img src="images/global/linkedin.svg" class="img-footer" onclick="">
        <img src="images/global/facebook.svg" class="img-footer" onclick="">
        <img src="images/global/email.svg" class="img-footer" onclick="">
        <label class="label-footer">+55 (15) 5555-5555</label>
    </footer>


    <!--Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous">
    </script>

    <script src="scripts/manager-scripts/atribuir-teste.js"></script>
</body>
            
</html>