<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap / CSS -->
    <link rel="stylesheet" href="/styles/custom-visualizar-requisicoes-de-vagas.css">
    <link rel="stylesheet" href="/styles/pop-up.css">
    <title>Visualizar Requisições de Vagas</title>

    <script type="text/javascript">
    let experiencias = <?php echo json_encode($this->view->detalhesVagaExperiencia) ?>;
    let competencias = <?php echo json_encode($this->view->detalhesVagaCompetencia) ?>;
    let formacoes = <?php echo json_encode($this->view->detalhesVagaFormacao) ?>;
    let cargos = <?php echo json_encode($this->view->cargos) ?>;

    let departamentoSalvo = <?php echo json_encode($this->view->detalhesVaga->id_departamento) ?>;
    let cargoSalvo = <?php echo json_encode($this->view->detalhesVaga->id_cargo) ?>;
    let vinculoSalvo = <?php echo json_encode($this->view->detalhesVaga->vinculo_emp) ?>;
    </script>
</head>

<?php if($_SESSION['tipo_user'] == 3) { ?>

<body>
    <!--Header-->
    <nav class="navbar navbar-expand-lg navbar-dark" id="header">
        <div class="container-fluid background-navbar">

            <a class="navbar-brand" href="/"><img src="images/global/logo.svg" alt=""></a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">

                <img src="images/global/navbar-button.svg" class="navbar-button">
            </button>

            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <!--gestor-->
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" href="/home">Home</a>
                        <a class="nav-link" href="">Gestor</a>
                        <a class="nav-link active" href="/requisicoes_vaga">Requisições</a>
                        <a class="nav-link" href="/gerenciar_processo_seletivo">Processos Seletivos</a>
                        <a class="nav-link" href="/gerenciar_entrevista_candidato">Entrevistas</a>
                        <a class="nav-link" href="/usuario_sair">Sair</a>
                    </div>
                </div>
            </div>
        </div>
    </nav>

    <!--Pop-up area-->
    <div class="popup-container" id="popup-confirm">
        <!--onclick="Open('popup-confirm')"-->
        <!--<link rel="stylesheet" href="../../../../Public/styles/pop-up.css">-->
        <!--<script src="../../../../Public/scripts/general-scripts/pop-up.js"></script>-->
        <div class="popup-content">
            <div class="popup-close" title="Close">
                <img src="/images/global/close.svg" onclick="Close(this)">
            </div>

            <img src="/images/pop-up/alert.svg" class="popup-img">

            <h1 class="popup-title">Alterar Requisição</h1>

            <p class="popup-description">Tem certeza que deseja alterar essa requisição?</p>

            <button class="popup-btn popup-btn-width" onclick="Confirm(this)">
                Confirmar
            </button>

            <button type="button" class="popup-btn-link" onclick="Close(this)">
                Voltar
            </button>
        </div>
    </div>

    <div class="popup-container" id="popup-confirm-2">
        <!--onclick="Open('popup-confirm')"-->
        <!--<link rel="stylesheet" href="../../../../Public/styles/pop-up.css">-->
        <!--<script src="../../../../Public/scripts/general-scripts/pop-up.js"></script>-->
        <div class="popup-content">
            <div class="popup-close" title="Close">
                <img src="/images/global/close.svg" onclick="Close(this)">
            </div>

            <img src="/images/pop-up/alert.svg" class="popup-img">

            <h1 class="popup-title">Excluir Requisição</h1>

            <p class="popup-description">Tem certeza que deseja excluir essa requisição?</p>

            <button class="popup-btn popup-btn-width" onclick="Confirm(this)">
                Confirmar
            </button>

            <button type="button" class="popup-btn-link" onclick="Close(this)">
                Voltar
            </button>
        </div>
    </div>

    <!--Pop-up de redirecionar página-->
    <div class="popup-container" id="popup-back">
        <!--onclick="Open('popup-back')"-->
        <!--<link rel="stylesheet" href="../../../../Public/styles/pop-up.css">-->
        <!--<script src="../../../../Public/scripts/general-scripts/pop-up.js"></script>-->
        <div class="popup-content">
            <div class="popup-close" title="Close">
                <img src="/images/global/close.svg" onclick="Close(this)">
            </div>

            <img src="/images/pop-up/alert.svg" class="popup-img">

            <h1 class="popup-title">Voltar</h1>

            <p class="popup-description">Tem certeza que deseja voltar para a página anterior? Todas as alterações
                realizadas serão perdidas.</p>

            <button class="popup-btn popup-btn-width" onclick="Back(this, '/requisicoes_vaga')">
                Confirmar
            </button>

            <button type="button" class="popup-btn-link" onclick="Close(this)">
                Voltar
            </button>
        </div>
    </div>

    <!--Page user-->
    <form action="alterar_vaga" method="post" id="formulario">
        <div class="container">

            <div class="title">
                <h1 class="title-1">Visualizar Requisição</h1>
            </div>

            <!--Dados de Solicitaçao-->
            <div class="title">
                <h2 class="title-2">Dados de Solicitação</h2>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="colsm-2 form-label title-interview">Título da Vaga</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control edit form1" id="colFormLabel" placeholder=""
                        name="titulo_vaga" value="<?= $this->view->detalhesVaga->titulo_vaga ?>">
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="colsm-2 form-label">Requisitante</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control edit form1" id="colFormLabel" placeholder=""
                        name="requisitante" readonly value="<?= $this->view->detalhesVaga->nome ?>">
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Data de Solicitação</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control edit form1" id="colFormLabel" placeholder=""
                        name="data-de-solicitacao" readonly value="<?= $this->view->detalhesVaga->data_solic ?>">
                </div>
            </div>

            <?php 
                $status = $this->view->detalhesVaga->status_vaga;
            ?>

            <div class="row mb-3 vagas">
                <!--6%-->
                <div class="title">
                    <h2 class="title-2">Status</h2>
                </div>
                <div class="mb-3 vaga" id="1-etapa">

                    <div class="vaga-bar">
                        <div class="vaga-per-6" per="6%"></div>
                    </div>

                    <div class="mb-3 texts">
                        <div class="text-box">
                            <span>Aberta</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Em Análise</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Aprovada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Vaga Criada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Finalizada</span>
                            <img src="">
                        </div>
                    </div>
                </div>

                <!--24%-->
                <div class="mb-3 vaga" id="2-etapa">
                    <div class="vaga-bar">
                        <div class="vaga-per-24" per="24%"></div>
                    </div>

                    <div class="mb-3 texts">
                        <div class="text-box">
                            <span>Aberta</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Em Análise</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Aprovada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Vaga Criada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Finalizada</span>
                            <img src="">
                        </div>
                    </div>

                </div>

                <!--59%-->
                <div class="mb-3 vaga" id="3-etapa">
                    <div class="vaga-bar">
                        <div class="vaga-per-59" per="59%"></div>
                    </div>

                    <div class="mb-3 texts">
                        <div class="text-box">
                            <span>Aberta</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Em Análise</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Aprovada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Vaga Criada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Finalizada</span>
                            <img src="">
                        </div>
                    </div>

                </div>

                <!--77%-->
                <div class="vaga" id="4-etapa">
                    <div class="vaga-bar">
                        <div class="vaga-per-77" per="77%"></div>
                    </div>

                    <div class="mb-3 texts">
                        <div class="text-box">
                            <span>Aberta</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Em Análise</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Aprovada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Vaga Criada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Finalizada</span>
                            <img src="">
                        </div>
                    </div>

                </div>

                <!--100%-->
                <div class="vaga" id="5-etapa">
                    <div class="vaga-bar">
                        <div class="vaga-per-100" per="100%"></div>
                    </div>

                    <div class="mb-3 texts">
                        <div class="text-box">
                            <span>Aberta</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Em Análise</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Aprovada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Vaga Criada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Finalizada</span>
                            <img src="">
                        </div>
                    </div>

                </div>
            </div>

            <!--Dados de Vaga-->
            <div class="title">
                <h2 class="title-2">Dados de Vaga</h2>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Departamento</label>
                <div class="col-sm-10">
                    <select class="col form-select form1" name="departamento" onchange="atribuitDept(this)">
                        <option value="0">--Selecione--</option>
                        <?php foreach ($this->view->departamentos as $key => $departamento) { ?>
                        <option value="<?=$departamento->id_departamento?>">
                            <?= $departamento->nome_departamento ?>
                        </option>
                        <?php } ?>
                    </select>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Cargo</label>
                <div class="col-sm-10">
                    <select class="col form-select form1" name="cargo">
                        <option value="0">--Selecione--</option>
                        <?php foreach ($this->view->cargos as $key => $cargo) { ?>
                        <option value="<?=$cargo->id_cargo?>">
                            <?= $cargo->nome_cargo ?>
                        </option>
                        <?php } ?>
                    </select>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Vínculo Empregatício</label>
                <div class="col-sm-10">
                    <select class="col form-select form1" aria-label="Formação" name="vinculo_empregaticio">
                        <option value="0">--Selecione--</option>
                        <option value="1">CLT</option>
                        <option value="2">PJ</option>
                        <option value="3">Estágio</option>
                    </select>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Salário</label>
                <div class="col-sm-10">
                    <input type="number" class="form-control edit form1" id="colFormLabel" placeholder="" name="salario"
                        min="0" value="<?= $this->view->detalhesVaga->salario ?>">
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Horário de Trabalho</label>
                <div class="col-sm-10 input-1">
                    <input type="time" class="form-control edit form2" id="colFormLabel" placeholder=""
                        name="hora-trab-inicio" value="<?= $this->view->detalhesVaga->hora_inicio ?>">
                </div>
                <label for="colFormLabel" class="col label-middle">à</label>
                <div class="col-sm-10 input-2">
                    <input type="time" class="form-control edit form2" id="colFormLabel" placeholder=""
                        name="hora-trab-fim" value="<?= $this->view->detalhesVaga->hora_fim ?>">
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Número de Vagas</label>
                <div class="col-sm-10">
                    <input type="number" class="form-control edit form1" id="colFormLabel" placeholder=""
                        name="numero-de-vagas" min="0" value="<?= $this->view->detalhesVaga->num_vagas ?>">
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Função</label>
                <div class="col-sm-12 mb-3">
                    <textarea type="text" class="form-control edit" id="textarea" rows="3"
                        name="funcao"><?= $this->view->detalhesVaga->funcao ?></textarea>
                </div>
            </div>

            <!--Experiências-->
            <div class="title">
                <h2 class="title-2">Experiências</h2>
            </div>

            <div id="Exp">
                <div class="subtitle">
                    <h3 class="title-3">Experiência</h3>
                    <h3 class="numExp">1</h3>
                </div>

                <div class="row mb-3">
                    <select class="col form-select cl-exp-formacao edit form3" aria-label="Formação"
                        name="exp-fomacao-1">
                        <option value="0">Experiência</option>
                        <option value="1">Administrativa</option>
                        <option value="2">Elétrica</option>
                        <option value="3">Eletrônica</option>
                        <option value="4">Recursos Humanos</option>
                        <option value="5">Redes</option>
                        <option value="6">Contábil</option>
                        <option value="7">Programação</option>
                        <option value="8">Logística</option>
                    </select>

                    <select class="col form-select cl-exp-status edit form3" aria-label="Status" name="exp-status-1">
                        <option value="0">Status</option>
                        <option value="1">Experiência Qualquer</option>
                        <option value="2">Júnior</option>
                        <option value="3">Pleno</option>
                        <option value="4">Sênior</option>
                    </select>
                </div>

                <div class="row">
                    <label for="colFormLabel" class="col-sm-2 form-label exp-label">Anos de Experiência:</label>
                    <div class="col number">
                        <input type="number" class="form-control cl-exp-anos-experiencia edit form2" id="colFormLabel"
                            placeholder="00" name="exp-anos-experiencia-1">
                    </div>
                </div>

                <div id="btn-area-0" class="btn-area-exp">
                    <img src="images/custom-requisicao-de-vaga/plus.svg" class="btn-form" onclick="addExp()">
                    <img src="images/custom-requisicao-de-vaga/minus.svg" class="btn-form" onclick="removeExp()">
                </div>
            </div>

            <!--Competências-->
            <div class="title">
                <h2 class="title-2">Competências</h2>
            </div>

            <div id="Comp">
                <div class="subtitle">
                    <h3 class="title-3">Competência</h3>
                    <h3 class="numComp">1</h3>
                </div>

                <div class="row mb-3">
                    <select class="col form-select cl-comp-nome edit form3" aria-label="Nome" name="comp-nome-1">
                        <option value="0">Nome</option>
                        <option value="1">Gestão de Pessoas</option>
                        <option value="2">Análise de Requisitos</option>
                        <option value="3">Java</option>
                        <option value="4">ERP</option>
                        <option value="5">Prestações de Contas</option>
                        <option value="6">Escrituração Fiscal</option>
                        <option value="7">Manutenção de Motores Trifásicos</option>
                        <option value="8">Gestão de Projetos</option>
                        <option value="9">Planejamento de Armazenagem de Mercadorias</option>
                        <option value="10">Inglês</option>
                    </select>

                    <select class="col form-select cl-comp-grau edit form3" aria-label="Grau" name="comp-grau-1">
                        <option value="0">Grau</option>
                        <option value="1">Básico</option>
                        <option value="2">Intermediário</option>
                        <option value="3">Avançado</option>
                    </select>
                </div>

                <div class="row">
                    <select class="col form-select cl-comp-status edit form4" aria-label="Status" name="comp-status-1">
                        <option value="0">Status</option>
                        <option value="1">Iniciante</option>
                        <option value="2">Em Desenvolvimento</option>
                        <option value="3">Concluído</option>
                    </select>
                </div>

                <div id="btn-area-comp-0" class="btn-area-comp">
                    <img src="images/custom-requisicao-de-vaga/plus.svg" class="btn-form" onclick="addComp()">
                    <img src="images/custom-requisicao-de-vaga/minus.svg" class="btn-form" onclick="removeComp()">
                </div>
            </div>

            <!--Formações-->
            <div class="title">
                <h2 class="title-2">Formações</h2>
            </div>

            <div id="Form">
                <div class="subtitle">
                    <h3 class="title-3">Formação</h3>
                    <h3 class="numForm">1</h3>
                </div>

                <div class="row mb-3">
                    <select class="col form-select cl-form-tipo edit form3" aria-label="Tipo" name="form-tipo-1">
                        <option value="0">Tipo</option>
                        <option value="1">Fundamental</option>
                        <option value="2">Ensino médio</option>
                        <option value="3">Técnico</option>
                        <option value="4">Superior</option>
                    </select>

                    <select class="col form-select cl-form-status edit form3" aria-label="Status" name="form-status-1">
                        <option value="0">Status</option>
                        <option value="1">Completo</option>
                        <option value="2">Em Andamento</option>
                        <option value="3">Incompleto</option>
                    </select>
                </div>

                <div class="row">
                    <select class="col form-select cl-form-nome edit form3" aria-label="Nome" name="form-nome-1">
                        <option value="0">Nome</option>
                        <option value="1">Análise e Desenvolvimento de Sistemas</option>
                        <option value="2">Redes</option>
                        <option value="3">Ciência da Computação</option>
                        <option value="4">Logística</option>
                        <option value="5">Contabilidade</option>
                        <option value="6">Engenharia Elétrica</option>
                        <option value="7">Engenharia Eletrônica</option>
                        <option value="8">Engenharia de Automação</option>
                        <option value="9">Recursos Humanos</option>
                        <option value="10">Administração</option>
                    </select>

                    <select class="col form-select cl-form-grau edit form3" aria-label="Grau" name="form-grau-1">
                        <option value="0">Grau</option>
                        <option value="1">Tecnólogo</option>
                        <option value="2">Graduação</option>
                        <option value="3">Pôs-graduação</option>
                        <option value="4">Mestrado</option>
                        <option value="4">Doutorado</option>
                    </select>
                </div>

                <div id="btn-area-form-0" class="btn-area-form">
                    <img src="images/custom-requisicao-de-vaga/plus.svg" class="btn-form" onclick="addForm()">
                    <img src="images/custom-requisicao-de-vaga/minus.svg" class="btn-form" onclick="removeForm()">
                </div>
            </div>

            <hr>

            <!--Comentário do Líder-->
            <div class="title">
                <h2 class="title-2">Comentários</h2>
            </div>

            <div class="row mb-3">
                <div class="col-sm-12 mb-3">
                    <textarea type="text" class="form-control edit" id="textarea" rows="3" name="comentario" readonly
                        tabindex="-1"><?= $this->view->detalhesVaga->comentario ?></textarea>
                </div>
            </div>

            <div class="buttons">
                <button type="button" class="btn btn-outline-primary mb-5" onclick="Open('popup-back')">Voltar</button>
                <button type="button" class="btn excluir btn-outline-primary mb-5"
                    onclick="Open('popup-confirm-2')">Excluir</button>
                <button type="button" class="btn aprovar btn-outline-primary mb-5"
                    onclick="Open('popup-confirm')">Salvar</button>
            </div>
        </div>
    </form>

    <!--Footer-->
    <footer class="footer">
        <img src="images/global/linkedin.svg" class="img-footer" onclick="">
        <img src="images/global/facebook.svg" class="img-footer" onclick="">
        <img src="images/global/email.svg" class="img-footer" onclick="">
        <label class="label-footer">+55 (15) 5555-5555</label>
    </footer>

    <!--Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous">
    </script>

    <script src="/scripts/manager-scripts/gerar-requisicao-de-vaga.js"></script>
    <script src="/scripts/general-scripts/pop-up.js"></script>
</body>
<?php } elseif($_SESSION['tipo_user'] == 4) { ?>

    <body>
    <!--Header-->
    <nav class="navbar navbar-expand-lg navbar-dark" id="header">
        <div class="container-fluid background-navbar">

            <a class="navbar-brand" href="/"><img src="images/global/logo.svg" alt=""></a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">

                <img src="images/global/navbar-button.svg" class="navbar-button">
            </button>

            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <!--gestor-->
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" href="/home">Home</a>
                        <a class="nav-link" href="">Líder</a>
                        <a class="nav-link active" href="/requisicoes_vaga">Requisições</a>
                        <a class="nav-link" href="/gerenciar_processo_seletivo">Processos Seletivos</a>
                        <a class="nav-link" href="/gerenciar_entrevista_candidato">Entrevistas</a>
                        <a class="nav-link" href="/usuario_sair">Sair</a>
                    </div>
                </div>
            </div>
        </div>
    </nav>

    <!--Pop-up area-->
    <div class="popup-container" id="popup-confirm">
        <!--onclick="Open('popup-confirm')"-->
        <!--<link rel="stylesheet" href="../../../../Public/styles/pop-up.css">-->
        <!--<script src="../../../../Public/scripts/general-scripts/pop-up.js"></script>-->
        <div class="popup-content">
            <div class="popup-close" title="Close">
                <img src="/images/global/close.svg" onclick="Close(this)">
            </div>

            <img src="/images/pop-up/alert.svg" class="popup-img">

            <h1 class="popup-title">Aprovar Requisição</h1>

            <p class="popup-description">Tem certeza que deseja aprovar essa requisição?</p>

            <button class="popup-btn popup-btn-width" onclick="Confirm(this, '/vaga_aprovar')">
                Confirmar
            </button>

            <button type="button" class="popup-btn-link" onclick="Close(this)">
                Voltar
            </button>
        </div>
    </div>

    <div class="popup-container" id="popup-confirm-2">
        <!--onclick="Open('popup-confirm')"-->
        <!--<link rel="stylesheet" href="../../../../Public/styles/pop-up.css">-->
        <!--<script src="../../../../Public/scripts/general-scripts/pop-up.js"></script>-->
        <div class="popup-content">
            <div class="popup-close" title="Close">
                <img src="/images/global/close.svg" onclick="Close(this)">
            </div>

            <img src="/images/pop-up/alert.svg" class="popup-img">

            <h1 class="popup-title">Reprovar Requisição</h1>

            <p class="popup-description">Tem certeza que deseja reprovar essa requisição?</p>

            <button class="popup-btn popup-btn-width" onclick="Confirm(this)">
                Confirmar
            </button>

            <button type="button" class="popup-btn-link" onclick="Close(this)">
                Voltar
            </button>
        </div>
    </div>

    <!--Pop-up de redirecionar página-->
    <div class="popup-container" id="popup-back">
        <!--onclick="Open('popup-back')"-->
        <!--<link rel="stylesheet" href="../../../../Public/styles/pop-up.css">-->
        <!--<script src="../../../../Public/scripts/general-scripts/pop-up.js"></script>-->
        <div class="popup-content">
            <div class="popup-close" title="Close">
                <img src="/images/global/close.svg" onclick="Close(this)">
            </div>

            <img src="/images/pop-up/alert.svg" class="popup-img">

            <h1 class="popup-title">Voltar</h1>

            <p class="popup-description">Tem certeza que deseja voltar para a página anterior? Todas as alterações
                realizadas serão perdidas.</p>

            <button class="popup-btn popup-btn-width" onclick="Back(this, '/requisicoes_vaga')">
                Confirmar
            </button>

            <button type="button" class="popup-btn-link" onclick="Close(this)">
                Voltar
            </button>
        </div>
    </div>

    <!--Page user-->
    <form action="vaga_aprovar" method="post" id="formulario">
        <div class="container">

            <div class="title">
                <h1 class="title-1">Visualizar Requisição</h1>
            </div>

            <!--Dados de Solicitaçao-->
            <div class="title">
                <h2 class="title-2">Dados de Solicitação</h2>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="colsm-2 form-label title-interview">Título da Vaga</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control edit form1" id="colFormLabel" placeholder=""
                        name="titulo_vaga" value="<?= $this->view->detalhesVaga->titulo_vaga ?>" disabled>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="colsm-2 form-label">Requisitante</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control edit form1" id="colFormLabel" placeholder=""
                        name="requisitante" readonly value="<?= $this->view->detalhesVaga->nome ?>" disabled>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Data de Solicitação</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control edit form1" id="colFormLabel" placeholder=""
                        name="data-de-solicitacao" readonly value="<?= $this->view->detalhesVaga->data_solic ?>" disabled>
                </div>
            </div>

            <?php 
                $status = $this->view->detalhesVaga->status_vaga;
            ?>

            <div class="row mb-3 vagas">
                <!--6%-->
                <div class="title">
                    <h2 class="title-2">Status</h2>
                </div>
                <div class="mb-3 vaga" id="1-etapa">

                    <div class="vaga-bar">
                        <div class="vaga-per-6" per="6%"></div>
                    </div>

                    <div class="mb-3 texts">
                        <div class="text-box">
                            <span>Aberta</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Em Análise</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Aprovada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Vaga Criada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Finalizada</span>
                            <img src="">
                        </div>
                    </div>
                </div>

                <!--24%-->
                <div class="mb-3 vaga" id="2-etapa">
                    <div class="vaga-bar">
                        <div class="vaga-per-24" per="24%"></div>
                    </div>

                    <div class="mb-3 texts">
                        <div class="text-box">
                            <span>Aberta</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Em Análise</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Aprovada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Vaga Criada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Finalizada</span>
                            <img src="">
                        </div>
                    </div>

                </div>

                <!--59%-->
                <div class="mb-3 vaga" id="3-etapa">
                    <div class="vaga-bar">
                        <div class="vaga-per-59" per="59%"></div>
                    </div>

                    <div class="mb-3 texts">
                        <div class="text-box">
                            <span>Aberta</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Em Análise</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Aprovada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Vaga Criada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Finalizada</span>
                            <img src="">
                        </div>
                    </div>

                </div>

                <!--77%-->
                <div class="vaga" id="4-etapa">
                    <div class="vaga-bar">
                        <div class="vaga-per-77" per="77%"></div>
                    </div>

                    <div class="mb-3 texts">
                        <div class="text-box">
                            <span>Aberta</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Em Análise</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Aprovada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Vaga Criada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Finalizada</span>
                            <img src="">
                        </div>
                    </div>

                </div>

                <!--100%-->
                <div class="vaga" id="5-etapa">
                    <div class="vaga-bar">
                        <div class="vaga-per-100" per="100%"></div>
                    </div>

                    <div class="mb-3 texts">
                        <div class="text-box">
                            <span>Aberta</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Em Análise</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Aprovada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Vaga Criada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Finalizada</span>
                            <img src="">
                        </div>
                    </div>

                </div>
            </div>

            <!--Dados de Vaga-->
            <div class="title">
                <h2 class="title-2">Dados de Vaga</h2>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Departamento</label>
                <div class="col-sm-10">
                    <select class="col form-select form1" name="departamento" onchange="atribuitDept(this)" disabled>
                        <option value="0">--Selecione--</option>
                        <?php foreach ($this->view->departamentos as $key => $departamento) { ?>
                        <option value="<?=$departamento->id_departamento?>">
                            <?= $departamento->nome_departamento ?>
                        </option>
                        <?php } ?>
                    </select>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Cargo</label>
                <div class="col-sm-10">
                    <select class="col form-select form1" name="cargo" disabled>
                        <option value="0">--Selecione--</option>
                        <?php foreach ($this->view->cargos as $key => $cargo) { ?>
                        <option value="<?=$cargo->id_cargo?>">
                            <?= $cargo->nome_cargo ?>
                        </option>
                        <?php } ?>
                    </select>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Vínculo Empregatício</label>
                <div class="col-sm-10">
                    <select class="col form-select form1" aria-label="Formação" name="vinculo_empregaticio" disabled>
                        <option value="0">--Selecione--</option>
                        <option value="1">CLT</option>
                        <option value="2">PJ</option>
                        <option value="3">Estágio</option>
                    </select>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Salário</label>
                <div class="col-sm-10">
                    <input type="number" class="form-control edit form1" id="colFormLabel" placeholder="" name="salario"
                        min="0" value="<?= $this->view->detalhesVaga->salario ?>" disabled>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Horário de Trabalho</label>
                <div class="col-sm-10 input-1">
                    <input type="time" class="form-control edit form2" id="colFormLabel" placeholder=""
                        name="hora-trab-inicio" value="<?= $this->view->detalhesVaga->hora_inicio ?>" disabled>
                </div>
                <label for="colFormLabel" class="col label-middle">à</label>
                <div class="col-sm-10 input-2">
                    <input type="time" class="form-control edit form2" id="colFormLabel" placeholder=""
                        name="hora-trab-fim" value="<?= $this->view->detalhesVaga->hora_fim ?>" disabled>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Número de Vagas</label>
                <div class="col-sm-10">
                    <input type="number" class="form-control edit form1" id="colFormLabel" placeholder=""
                        name="numero-de-vagas" min="0" value="<?= $this->view->detalhesVaga->num_vagas ?>" disabled>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Função</label>
                <div class="col-sm-12 mb-3">
                    <textarea type="text" class="form-control edit" id="textarea" rows="3"
                        name="funcao" disabled><?= $this->view->detalhesVaga->funcao ?></textarea>
                </div>
            </div>

            <!--Experiências-->
            <div class="title">
                <h2 class="title-2">Experiências</h2>
            </div>

            <div id="Exp">
                <div class="subtitle">
                    <h3 class="title-3">Experiência</h3>
                    <h3 class="numExp">1</h3>
                </div>

                <div class="row mb-3">
                    <select class="col form-select cl-exp-formacao edit form3" aria-label="Formação" disabled
                        name="exp-fomacao-1">
                        <option value="0">Experiência</option>
                        <option value="1">Administrativa</option>
                        <option value="2">Elétrica</option>
                        <option value="3">Eletrônica</option>
                        <option value="4">Recursos Humanos</option>
                        <option value="5">Redes</option>
                        <option value="6">Contábil</option>
                        <option value="7">Programação</option>
                        <option value="8">Logística</option>
                    </select>

                    <select class="col form-select cl-exp-status edit form3" aria-label="Status" name="exp-status-1" disabled>
                        <option value="0">Status</option>
                        <option value="1">Experiência Qualquer</option>
                        <option value="2">Júnior</option>
                        <option value="3">Pleno</option>
                        <option value="4">Sênior</option>
                    </select>
                </div>

                <div class="row">
                    <label for="colFormLabel" class="col-sm-2 form-label exp-label">Anos de Experiência:</label>
                    <div class="col number">
                        <input type="number" class="form-control cl-exp-anos-experiencia edit form2" id="colFormLabel"
                            placeholder="00" name="exp-anos-experiencia-1" disabled>
                    </div>
                </div>

                
            </div>

            <!--Competências-->
            <div class="title">
                <h2 class="title-2">Competências</h2>
            </div>

            <div id="Comp">
                <div class="subtitle">
                    <h3 class="title-3">Competência</h3>
                    <h3 class="numComp">1</h3>
                </div>

                <div class="row mb-3">
                    <select class="col form-select cl-comp-nome edit form3" aria-label="Nome" name="comp-nome-1" disabled>
                        <option value="0">Nome</option>
                        <option value="1">Gestão de Pessoas</option>
                        <option value="2">Análise de Requisitos</option>
                        <option value="3">Java</option>
                        <option value="4">ERP</option>
                        <option value="5">Prestações de Contas</option>
                        <option value="6">Escrituração Fiscal</option>
                        <option value="7">Manutenção de Motores Trifásicos</option>
                        <option value="8">Gestão de Projetos</option>
                        <option value="9">Planejamento de Armazenagem de Mercadorias</option>
                        <option value="10">Inglês</option>
                    </select>

                    <select class="col form-select cl-comp-grau edit form3" aria-label="Grau" name="comp-grau-1" disabled>
                        <option value="0">Grau</option>
                        <option value="1">Básico</option>
                        <option value="2">Intermediário</option>
                        <option value="3">Avançado</option>
                    </select>
                </div>

                <div class="row">
                    <select class="col form-select cl-comp-status edit form4" aria-label="Status" name="comp-status-1" disabled>
                        <option value="0">Status</option>
                        <option value="1">Iniciante</option>
                        <option value="2">Em Desenvolvimento</option>
                        <option value="3">Concluído</option>
                    </select>
                </div>

                
            </div>

            <!--Formações-->
            <div class="title">
                <h2 class="title-2">Formações</h2>
            </div>

            <div id="Form">
                <div class="subtitle">
                    <h3 class="title-3">Formação</h3>
                    <h3 class="numForm">1</h3>
                </div>

                <div class="row mb-3">
                    <select class="col form-select cl-form-tipo edit form3" aria-label="Tipo" name="form-tipo-1" disabled>
                        <option value="0">Tipo</option>
                        <option value="1">Fundamental</option>
                        <option value="2">Ensino médio</option>
                        <option value="3">Técnico</option>
                        <option value="4">Superior</option>
                    </select>

                    <select class="col form-select cl-form-status edit form3" aria-label="Status" name="form-status-1" disabled>
                        <option value="0">Status</option>
                        <option value="1">Completo</option>
                        <option value="2">Em Andamento</option>
                        <option value="3">Incompleto</option>
                    </select>
                </div>

                <div class="row">
                    <select class="col form-select cl-form-nome edit form3" aria-label="Nome" name="form-nome-1" disabled>
                        <option value="0">Nome</option>
                        <option value="1">Análise e Desenvolvimento de Sistemas</option>
                        <option value="2">Redes</option>
                        <option value="3">Ciência da Computação</option>
                        <option value="4">Logística</option>
                        <option value="5">Contabilidade</option>
                        <option value="6">Engenharia Elétrica</option>
                        <option value="7">Engenharia Eletrônica</option>
                        <option value="8">Engenharia de Automação</option>
                        <option value="9">Recursos Humanos</option>
                        <option value="10">Administração</option>
                    </select>

                    <select class="col form-select cl-form-grau edit form3" aria-label="Grau" name="form-grau-1" disabled>
                        <option value="0">Grau</option>
                        <option value="1">Tecnólogo</option>
                        <option value="2">Graduação</option>
                        <option value="3">Pôs-graduação</option>
                        <option value="4">Mestrado</option>
                        <option value="4">Doutorado</option>
                    </select>
                </div>

                
            </div>

            <hr>

            <!--Comentário do Líder-->
            <div class="title">
                <h2 class="title-2">Comentários</h2>
            </div>

            <div class="row mb-3">
                <div class="col-sm-12 mb-3">
                    <textarea type="text" class="form-control edit" id="textarea" rows="3" name="comentario"
                        tabindex="-1"><?= $this->view->detalhesVaga->comentario ?></textarea>
                    <input type="hidden" name="id_vaga" value="<?= $this->view->detalhesVaga->id_vaga ?>" readonly>
                </div>
            </div>
                            
            <div class="buttons">
                <button type="button" class="btn btn-outline-primary mb-5" onclick="Open('popup-back')">Voltar</button>
                <button type="button" class="btn excluir btn-outline-primary mb-5"
                    onclick="Open('popup-confirm-2')">Reprovar</button>
                <button type="button" class="btn aprovar btn-outline-primary mb-5"
                    onclick="Open('popup-confirm')">Aprovar</button>
            </div>
        </div>
    </form>

    <!--Footer-->
    <footer class="footer">
        <img src="images/global/linkedin.svg" class="img-footer" onclick="">
        <img src="images/global/facebook.svg" class="img-footer" onclick="">
        <img src="images/global/email.svg" class="img-footer" onclick="">
        <label class="label-footer">+55 (15) 5555-5555</label>
    </footer>

    <!--Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous">
    </script>

    <script src="/scripts/manager-scripts/gerar-requisicao-de-vaga.js"></script>
    <script src="/scripts/general-scripts/pop-up.js"></script>
</body>
<?php } else{ ?>

<body>
    <!--Header-->
    <nav class="navbar navbar-expand-lg navbar-dark" id="header">
        <div class="container-fluid background-navbar">

            <a class="navbar-brand" href="/"><img src="images/global/logo.svg" alt=""></a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">

                <img src="images/global/navbar-button.svg" class="navbar-button">
            </button>

            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <!--gestor-->
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" href="/home">Home</a>
                        <a class="nav-link" href="">Gestor</a>
                        <a class="nav-link active" href="/requisicoes_vaga">Requisições</a>
                        <a class="nav-link" href="/gerenciar_vaga">Vagas</a>
                        <a class="nav-link" href="/gerenciar_processo_seletivo">Processos Seletivos</a>
                        <a class="nav-link" href="/gerenciar_entrevista_candidato">Entrevistas</a>
                        <a class="nav-link" href="/usuario_sair">Sair</a>
                    </div>
                </div>
            </div>
        </div>
    </nav>

    <!--Pop-up area-->
    <div class="popup-container" id="popup-confirm">
        <!--onclick="Open('popup-confirm')"-->
        <!--<link rel="stylesheet" href="../../../../Public/styles/pop-up.css">-->
        <!--<script src="../../../../Public/scripts/general-scripts/pop-up.js"></script>-->
        <div class="popup-content">
            <div class="popup-close" title="Close">
                <img src="/images/global/close.svg" onclick="Close(this)">
            </div>

            <img src="/images/pop-up/alert.svg" class="popup-img">

            <h1 class="popup-title">Alterar Requisição</h1>

            <p class="popup-description">Tem certeza que deseja alterar essa requisição?</p>

            <button class="popup-btn popup-btn-width" onclick="Confirm(this)">
                Confirmar
            </button>

            <button type="button" class="popup-btn-link" onclick="Close(this)">
                Voltar
            </button>
        </div>
    </div>

    <div class="popup-container" id="popup-confirm-2">
        <!--onclick="Open('popup-confirm')"-->
        <!--<link rel="stylesheet" href="../../../../Public/styles/pop-up.css">-->
        <!--<script src="../../../../Public/scripts/general-scripts/pop-up.js"></script>-->
        <div class="popup-content">
            <div class="popup-close" title="Close">
                <img src="/images/global/close.svg" onclick="Close(this)">
            </div>

            <img src="/images/pop-up/alert.svg" class="popup-img">

            <h1 class="popup-title">Excluir Requisição</h1>

            <p class="popup-description">Tem certeza que deseja excluir essa requisição?</p>

            <button class="popup-btn popup-btn-width" onclick="Confirm(this)">
                Confirmar
            </button>

            <button type="button" class="popup-btn-link" onclick="Close(this)">
                Voltar
            </button>
        </div>
    </div>

    <!--Pop-up de redirecionar página-->
    <div class="popup-container" id="popup-back">
        <!--onclick="Open('popup-back')"-->
        <!--<link rel="stylesheet" href="../../../../Public/styles/pop-up.css">-->
        <!--<script src="../../../../Public/scripts/general-scripts/pop-up.js"></script>-->
        <div class="popup-content">
            <div class="popup-close" title="Close">
                <img src="/images/global/close.svg" onclick="Close(this)">
            </div>

            <img src="/images/pop-up/alert.svg" class="popup-img">

            <h1 class="popup-title">Voltar</h1>

            <p class="popup-description">Tem certeza que deseja voltar para a página anterior? Todas as alterações
                realizadas serão perdidas.</p>

            <button class="popup-btn popup-btn-width" onclick="Back(this, '/requisicoes_vaga')">
                Confirmar
            </button>

            <button type="button" class="popup-btn-link" onclick="Close(this)">
                Voltar
            </button>
        </div>
    </div>

    <!--Page user-->
    <form action="alterar_vaga" method="post" id="formulario">
        <div class="container">

            <div class="title">
                <h1 class="title-1">Visualizar Requisição</h1>
            </div>

            <!--Dados de Solicitaçao-->
            <div class="title">
                <h2 class="title-2">Dados de Solicitação</h2>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="colsm-2 form-label title-interview">Título da Vaga</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control edit form1" id="colFormLabel" placeholder=""
                        name="titulo_vaga" value="<?= $this->view->detalhesVaga->titulo_vaga ?>">
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="colsm-2 form-label">Requisitante</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control edit form1" id="colFormLabel" placeholder=""
                        name="requisitante" readonly value="<?= $this->view->detalhesVaga->nome ?>">
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Data de Solicitação</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control edit form1" id="colFormLabel" placeholder=""
                        name="data-de-solicitacao" readonly value="<?= $this->view->detalhesVaga->data_solic ?>">
                </div>
            </div>

            <?php 
                $status = $this->view->detalhesVaga->status_vaga;
            ?>

            <div class="row mb-3 vagas">
                <!--6%-->
                <div class="mb-3 vaga" id="1-etapa">
                    <div class="title">
                        <h2 class="title-2">Status</h2>
                    </div>

                    <div class="vaga-bar">
                        <div class="vaga-per-6" per="6%"></div>
                    </div>

                    <div class="mb-3 texts">
                        <div class="text-box">
                            <span>Aberta</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Em Análise</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Aprovada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Vaga Criada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Finalizada</span>
                            <img src="">
                        </div>
                    </div>
                </div>

                <!--28%-->
                <div class="mb-3 vaga" id="2-etapa">
                    <div class="vaga-bar">
                        <div class="vaga-per-24" per="28%"></div>
                    </div>

                    <div class="mb-3 texts">
                        <div class="text-box">
                            <span>Aberta</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Em Análise</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Aprovada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Vaga Criada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Finalizada</span>
                            <img src="">
                        </div>
                    </div>

                </div>

                <!--50%-->
                <div class="mb-3 vaga" id="3-etapa">
                    <div class="vaga-bar">
                        <div class="vaga-per-59" per="50%"></div>
                    </div>

                    <div class="mb-3 texts">
                        <div class="text-box">
                            <span>Aberta</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Em Análise</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Aprovada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Vaga Criada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Finalizada</span>
                            <img src="">
                        </div>
                    </div>

                </div>

                <!--72%-->
                <div class="vaga" id="4-etapa">
                    <div class="vaga-bar">
                        <div class="vaga-per-77" per="72%"></div>
                    </div>

                    <div class="mb-3 texts">
                        <div class="text-box">
                            <span>Aberta</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Em Análise</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Aprovada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Vaga Criada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Finalizada</span>
                            <img src="">
                        </div>
                    </div>

                </div>

                <!--100%-->
                <div class="vaga" id="5-etapa">
                    <div class="vaga-bar">
                        <div class="vaga-per-100" per="100%"></div>
                    </div>

                    <div class="mb-3 texts">
                        <div class="text-box">
                            <span>Aberta</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Em Análise</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Aprovada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Vaga Criada</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Finalizada</span>
                            <img src="">
                        </div>
                    </div>

                </div>
            </div>

            <!--Dados de Vaga-->
            <div class="title">
                <h2 class="title-2">Dados de Vaga</h2>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Departamento</label>
                <div class="col-sm-10">
                    <select class="col form-select form1" name="departamento" onchange="atribuitDept(this)">
                        <option value="0">--Selecione--</option>
                        <?php foreach ($this->view->departamentos as $key => $departamento) { ?>
                        <option value="<?=$departamento->id_departamento?>">
                            <?= $departamento->nome_departamento ?>
                        </option>
                        <?php } ?>
                    </select>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Cargo</label>
                <div class="col-sm-10">
                    <select class="col form-select form1" name="cargo">
                        <option value="0">--Selecione--</option>
                        <?php foreach ($this->view->cargos as $key => $cargo) { ?>
                        <option value="<?=$cargo->id_cargo?>">
                            <?= $cargo->nome_cargo ?>
                        </option>
                        <?php } ?>
                    </select>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Vínculo Empregatício</label>
                <div class="col-sm-10">
                    <select class="col form-select form1" aria-label="Formação" name="vinculo_empregaticio">
                        <option value="0">--Selecione--</option>
                        <option value="1">CLT</option>
                        <option value="2">PJ</option>
                        <option value="3">Estágio</option>
                    </select>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Salário</label>
                <div class="col-sm-10">
                    <input type="number" class="form-control edit form1" id="colFormLabel" placeholder="" name="salario"
                        min="0" value="<?= $this->view->detalhesVaga->salario ?>">
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Horário de Trabalho</label>
                <div class="col-sm-10 input-1">
                    <input type="time" class="form-control edit form2" id="colFormLabel" placeholder=""
                        name="hora-trab-inicio" value="<?= $this->view->detalhesVaga->hora_inicio ?>">
                </div>
                <label for="colFormLabel" class="col label-middle">à</label>
                <div class="col-sm-10 input-2">
                    <input type="time" class="form-control edit form2" id="colFormLabel" placeholder=""
                        name="hora-trab-fim" value="<?= $this->view->detalhesVaga->hora_fim ?>">
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Número de Vagas</label>
                <div class="col-sm-10">
                    <input type="number" class="form-control edit form1" id="colFormLabel" placeholder=""
                        name="numero-de-vagas" min="0" value="<?= $this->view->detalhesVaga->num_vagas ?>">
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Função</label>
                <div class="col-sm-12 mb-3">
                    <textarea type="text" class="form-control edit" id="textarea" rows="3"
                        name="funcao"><?= $this->view->detalhesVaga->funcao ?></textarea>
                </div>
            </div>

            <!--Experiências-->
            <div class="title">
                <h2 class="title-2">Experiências</h2>
            </div>

            <div id="Exp">
                <div class="subtitle">
                    <h3 class="title-3">Experiência</h3>
                    <h3 class="numExp">1</h3>
                </div>

                <div class="row mb-3">
                    <select class="col form-select cl-exp-formacao edit form3" aria-label="Formação"
                        name="exp-fomacao-1">
                        <option value="0">Experiência</option>
                        <option value="1">Administrativa</option>
                        <option value="2">Elétrica</option>
                        <option value="3">Eletrônica</option>
                        <option value="4">Recursos Humanos</option>
                        <option value="5">Redes</option>
                        <option value="6">Contábil</option>
                        <option value="7">Programação</option>
                        <option value="8">Logística</option>
                    </select>

                    <select class="col form-select cl-exp-status edit form3" aria-label="Status" name="exp-status-1">
                        <option value="0">Status</option>
                        <option value="1">Experiência Qualquer</option>
                        <option value="2">Júnior</option>
                        <option value="3">Pleno</option>
                        <option value="4">Sênior</option>
                    </select>
                </div>

                <div class="row">
                    <label for="colFormLabel" class="col-sm-2 form-label exp-label">Anos de Experiência:</label>
                    <div class="col number">
                        <input type="number" class="form-control cl-exp-anos-experiencia edit form2" id="colFormLabel"
                            placeholder="00" name="exp-anos-experiencia-1">
                    </div>
                </div>

                <div id="btn-area-0" class="btn-area-exp">
                    <img src="images/custom-requisicao-de-vaga/plus.svg" class="btn-form" onclick="addExp()">
                    <img src="images/custom-requisicao-de-vaga/minus.svg" class="btn-form" onclick="removeExp()">
                </div>
            </div>

            <!--Competências-->
            <div class="title">
                <h2 class="title-2">Competências</h2>
            </div>

            <div id="Comp">
                <div class="subtitle">
                    <h3 class="title-3">Competência</h3>
                    <h3 class="numComp">1</h3>
                </div>

                <div class="row mb-3">
                    <select class="col form-select cl-comp-nome edit form3" aria-label="Nome" name="comp-nome-1">
                        <option value="0">Nome</option>
                        <option value="1">Gestão de Pessoas</option>
                        <option value="2">Análise de Requisitos</option>
                        <option value="3">Java</option>
                        <option value="4">ERP</option>
                        <option value="5">Prestações de Contas</option>
                        <option value="6">Escrituração Fiscal</option>
                        <option value="7">Manutenção de Motores Trifásicos</option>
                        <option value="8">Gestão de Projetos</option>
                        <option value="9">Planejamento de Armazenagem de Mercadorias</option>
                        <option value="10">Inglês</option>
                    </select>

                    <select class="col form-select cl-comp-grau edit form3" aria-label="Grau" name="comp-grau-1">
                        <option value="0">Grau</option>
                        <option value="1">Básico</option>
                        <option value="2">Intermediário</option>
                        <option value="3">Avançado</option>
                    </select>
                </div>

                <div class="row">
                    <select class="col form-select cl-comp-status edit form4" aria-label="Status" name="comp-status-1">
                        <option value="0">Status</option>
                        <option value="1">Iniciante</option>
                        <option value="2">Em Desenvolvimento</option>
                        <option value="3">Concluído</option>
                    </select>
                </div>

                <div id="btn-area-comp-0" class="btn-area-comp">
                    <img src="images/custom-requisicao-de-vaga/plus.svg" class="btn-form" onclick="addComp()">
                    <img src="images/custom-requisicao-de-vaga/minus.svg" class="btn-form" onclick="removeComp()">
                </div>
            </div>

            <!--Formações-->
            <div class="title">
                <h2 class="title-2">Formações</h2>
            </div>

            <div id="Form">
                <div class="subtitle">
                    <h3 class="title-3">Formação</h3>
                    <h3 class="numForm">1</h3>
                </div>

                <div class="row mb-3">
                    <select class="col form-select cl-form-tipo edit form3" aria-label="Tipo" name="form-tipo-1">
                        <option value="0">Tipo</option>
                        <option value="1">Fundamental</option>
                        <option value="2">Ensino médio</option>
                        <option value="3">Técnico</option>
                        <option value="4">Superior</option>
                    </select>

                    <select class="col form-select cl-form-status edit form3" aria-label="Status" name="form-status-1">
                        <option value="0">Status</option>
                        <option value="1">Completo</option>
                        <option value="2">Em Andamento</option>
                        <option value="3">Incompleto</option>
                    </select>
                </div>

                <div class="row">
                    <select class="col form-select cl-form-nome edit form3" aria-label="Nome" name="form-nome-1">
                        <option value="0">Nome</option>
                        <option value="1">Análise e Desenvolvimento de Sistemas</option>
                        <option value="2">Redes</option>
                        <option value="3">Ciência da Computação</option>
                        <option value="4">Logística</option>
                        <option value="5">Contabilidade</option>
                        <option value="6">Engenharia Elétrica</option>
                        <option value="7">Engenharia Eletrônica</option>
                        <option value="8">Engenharia de Automação</option>
                        <option value="9">Recursos Humanos</option>
                        <option value="10">Administração</option>
                    </select>

                    <select class="col form-select cl-form-grau edit form3" aria-label="Grau" name="form-grau-1">
                        <option value="0">Grau</option>
                        <option value="1">Tecnólogo</option>
                        <option value="2">Graduação</option>
                        <option value="3">Pôs-graduação</option>
                        <option value="4">Mestrado</option>
                        <option value="4">Doutorado</option>
                    </select>
                </div>

                <div id="btn-area-form-0" class="btn-area-form">
                    <img src="images/custom-requisicao-de-vaga/plus.svg" class="btn-form" onclick="addForm()">
                    <img src="images/custom-requisicao-de-vaga/minus.svg" class="btn-form" onclick="removeForm()">
                </div>
            </div>

            <hr>

            <!--Comentário do Líder-->
            <div class="title">
                <h2 class="title-2">Comentários</h2>
            </div>

            <div class="row mb-3">
                <div class="col-sm-12 mb-3">
                    <textarea type="text" class="form-control edit" id="textarea" rows="3" name="comentario"
                        tabindex="-1"><?= $this->view->detalhesVaga->comentario ?></textarea>
                        <input type="hidden" name="id_vaga" value="<?= $this->view->detalhesVaga->id_vaga ?>" readonly hidden> 
                </div>
            </div>

            <div class="buttons">
                <button type="button" class="btn btn-outline-primary mb-5" onclick="Open('popup-back')">Voltar</button>
                <button type="button" class="btn excluir btn-outline-primary mb-5"
                    onclick="Open('popup-confirm-2')">Excluir</button>
                <button type="button" class="btn aprovar btn-outline-primary mb-5"
                    onclick="Open('popup-confirm')">Salvar</button>
            </div>
        </div>
    </form>

    <!--Footer-->
    <footer class="footer">
        <img src="images/global/linkedin.svg" class="img-footer" onclick="">
        <img src="images/global/facebook.svg" class="img-footer" onclick="">
        <img src="images/global/email.svg" class="img-footer" onclick="">
        <label class="label-footer">+55 (15) 5555-5555</label>
    </footer>

    <!--Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous">
    </script>

    <script src="/scripts/manager-scripts/gerar-requisicao-de-vaga.js"></script>
    <script src="/scripts/general-scripts/pop-up.js"></script>
</body>
<?php } ?>

</html>

<script language="javascript">
var status = "<?php print $status; ?>";

document.getElementById('1-etapa').style.display = 'none';
document.getElementById('2-etapa').style.display = 'none';
document.getElementById('3-etapa').style.display = 'none';
document.getElementById('4-etapa').style.display = 'none';
document.getElementById('5-etapa').style.display = 'none';

if (status == 'Aberta')
    document.getElementById('1-etapa').style.display = 'block';
else if (status == 'Em Análise')
    document.getElementById('2-etapa').style.display = 'block';
else if (status == 'Aprovada')
    document.getElementById('3-etapa').style.display = 'block';
else if (status == 'Vaga Criada')
    document.getElementById('4-etapa').style.display = 'block';
else
    document.getElementById('5-etapa').style.display = 'block';

renderizaInformacoes();
insereExperiencia();
insereCompetencia();
insereFormacao();
</script>