<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap / CSS -->
    <link rel="stylesheet" href="/styles/pop-up.css">
    <link rel="stylesheet" href="/styles/custom-login.css">

    <title>Login</title>
</head>

<body>
    <!--Header-->
    <nav class="navbar navbar-expand-lg navbar-dark" id="header">
        <div class="container-fluid background-navbar">
            <a class="navbar-brand" href="#"><img src="/images/global/logo.svg" alt=""></a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">
                <img src="/images/global/navbar-button.svg" class="navbar-button">
            </button>

            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" aria-current="page" href="#">Home</a>
                    <a class="nav-link active" href="#">Entrar</a>
                    <a class="nav-link" href="#scroll-1">Sobre</a>
                    <a class="nav-link" href="#scroll-2">Quem Somos</a>
                    <a class="nav-link" href="#scroll-3">Nossos Líderes</a>
                    <a class="nav-link" href="#scroll-4">Trabalhe Conosco</a>
                    <a class="nav-link" href="#scroll-5">Contato</a>
                </div>
            </div>
        </div>
    </nav>

    <!--body-->
    <form action="requisitante.php" method="post">
        <div class="container">
            <div class="login-content">
                <h1>Login</h1>

                <div class="textbox">
                    <img src="/images/login/user.svg" onclick="Open('popup-info')">
                    <input type="text" placeholder="Nome de Usuário/E-mail" name="login">
                </div>

                <div class="textbox">
                    <img src="/images/login/lock.svg">
                    <input type="password" placeholder="Senha" name="login" id="password">
                    <img src="/images/login/eye-off.svg" id="eye-img" class="eye">
                </div>
            </div>

            <!--Pop-up de informação-->
            <div class="popup-container" id="popup-info">
                <!--onclick="Open('popup-info')"-->
                <!--<link rel="stylesheet" href="../../../../Public/styles/pop-up.css">-->
                <!--<script src="../../../../Public/scripts/general-scripts/pop-up.js"></script>-->
                <div class="popup-content">
                    <div class="popup-close" title="Close" onclick="Close(this)">
                        <img src="/images/global/close.svg">
                    </div>

                    <img src="/images/pop-up/info.svg" class="popup-img">

                    <h1 class="popup-title">Informação!</h1>

                    <p class="popup-description">Escreva a informação aqui!</p>

                    <button type="button" class="popup-btn popup-btn-width" onclick="Close(this)">
                        Entendi!
                    </button>
                </div>
            </div>

            <!--Pop-up de atribuição-->
            <div class="popup-container" id="popup-confirm">
                <!--onclick="Open('popup-confirm')"-->
                <!--<link rel="stylesheet" href="../../../../Public/styles/pop-up.css">-->
                <!--<script src="../../../../Public/scripts/general-scripts/pop-up.js"></script>-->
                <div class="popup-content">
                    <div class="popup-close" title="Close" onclick="Close(this)">
                        <img src="/images/global/close.svg">
                    </div>

                    <img src="/images/pop-up/alert.svg" class="popup-img">

                    <h1 class="popup-title">Informação!</h1>

                    <p class="popup-description">Escreva a informação aqui!</p>

                    <button class="popup-btn popup-btn-width" onclick="Confirm(this)">
                        Confirmar
                    </button>

                    <button type="button" class="popup-btn-link" onclick="Close(this)">
                        Voltar
                    </button>
                </div>
            </div>

            <!--Pop-up de redirecionar página-->
            <div class="popup-container" id="popup-back">
                <!--onclick="Open('popup-back')"-->
                <!--<link rel="stylesheet" href="../../../../Public/styles/pop-up.css">-->
                <!--<script src="../../../../Public/scripts/general-scripts/pop-up.js"></script>-->
                <div class="popup-content">
                    <div class="popup-close" title="Close" onclick="Close(this)">
                        <img src="/images/global/close.svg">
                    </div>

                    <img src="/images/pop-up/alert.svg" class="popup-img">

                    <h1 class="popup-title">Informação!</h1>

                    <p class="popup-description">Escreva sua mensagem aqui!</p>

                    <button class="popup-btn popup-btn-width" onclick="Back(this, 'url')">
                        Confirmar
                    </button>

                    <button type="button" class="popup-btn-link" onclick="Close(this)">
                        Voltar
                    </button>
                </div>
            </div>
        </div>
    </form>

    <!--Footer-->
    <footer class="footer">
        <img src="/images/global/linkedin.svg" class="img-footer" onclick="">
        <img src="/images/global/facebook.svg" class="img-footer" onclick="">
        <img src="/images/global/email.svg" class="img-footer" onclick="">
        <label class="label-footer">+55 (15) 5555-5555</label>
    </footer>

    <!--Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous">
    </script>

    <script src="/scripts/general-scripts/login.js"></script>
    <script src="/scripts/general-scripts/pop-up.js"></script>
</body>

</html>