<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap / CSS -->
    <link rel="stylesheet" href="/styles/custom-registro.css">

    <title>Registro</title>
</head>

<body>
    <!--Header-->
    <nav class="navbar navbar-expand-lg navbar-dark" id="header">
        <div class="container-fluid background-navbar">
            <a class="navbar-brand" href="/home"><img src="/images/global/logo.svg" alt=""></a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">
                <img src="/images/global/navbar-button.svg" class="navbar-button">
            </button>

            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" aria-current="page" href="/home">Home</a>
                    <a class="nav-link active" href="/usuario_entrar">Entrar</a>
                    <a class="nav-link" href="/home#sobre_nos">Sobre</a>
                    <a class="nav-link" href="/home#quem_somos">Quem Somos</a>
                    <a class="nav-link" href="/home#nossa_equipe">Nossos Líderes</a>
                    <a class="nav-link" href="/home#vagas_abertas">Trabalhe Conosco</a>
                    <a class="nav-link" href="/home#contate_nos">Contato</a>
                </div>
            </div>
        </div>
    </nav>

    <?php
    if (isset($_GET['usuarioCadastrar'])) {
    ?>

        <script>
            alert("Usuário Salvo com Sucesso!");
        </script>

    <?php
    }
    ?>

    <!--body-->
    <form action="/usuario_cadastrar_salvar" method="post" id="myForm">
        <div class="container">
            <div class="login-content">
                <h1>Registro</h1>

                <div class="textbox">
                    <img src="/images/login/user.svg">
                    <input type="text" placeholder="Nome de Usuário/E-mail" name="login" id="login">
                </div>

                <div class="textbox">
                    <img class="img-email" src="/images/global/email.svg">
                    <input type="email" placeholder="E-mail" name="email" id="email">
                </div>

                <div class="textbox">
                    <img class="img-email" src="/images/global/email.svg">
                    <input type="email" placeholder="Repetir E-mail" name="email-repetido" id="email-2">
                </div>

                <div class="textbox">
                    <img src="/images/login/user.svg">
                    <input type="textbox" placeholder="Nome" name="nome" id="nome">
                </div>

                <div class="textbox">
                    <img src="/images/login/lock.svg">
                    <input type="password" placeholder="Senha" name="senha" id="password">
                    <img src="/images/login/eye-off.svg" id="eye-img" class="eye">
                </div>

                <div class="textbox txt">
                    <img src="/images/login/lock.svg">
                    <input type="password" placeholder="Repetir Senha" name="senha-repetida" id="password-2">
                    <img src="/images/login/eye-off.svg" id="eye-img-2" class="eye">
                </div>

                <a class="btn-link" onclick="cadastrar()">
                        <div class="effect">
                            <span>Cadastrar</span>
                            <input class="btn" type="submit" value="Cadastrar">
                        </div>
                </a>

                <a class="btn-link" href="/usuario_entrar">
                    <div class="effect">
                        <span>Voltar</span>
                        <input class="btn" type="button">
                    </div>
                </a>

            </div>
        </div>
    </form>

    <!--Footer-->
    <footer class="footer">
        <img src="/images/global/linkedin.svg" class="img-footer" onclick="">
        <img src="/images/global/facebook.svg" class="img-footer" onclick="">
        <img src="/images/global/email.svg" class="img-footer" onclick="">
        <label class="label-footer">+55 (15) 5555-5555</label>
    </footer>

    <!--Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ"
        crossorigin="anonymous"></script>

    <script src="/scripts/general-scripts/login.js"></script>
</body>

</html>